-- Core infrastructure tables shared by every module.
-- Applied automatically by pipeline.db.apply_migrations before any module runs.
--
-- PostgreSQL dialect of ../0001_core.sql. See README.md in this directory for
-- the conversion rules; the comments below are the originals except where the
-- port made a choice worth recording.

CREATE TABLE IF NOT EXISTS schema_migrations (
    filename    text PRIMARY KEY,
    applied_at  text NOT NULL
);

-- Constraint 6: fail loudly, never silently guess. A field that could not be
-- parsed is written as NULL and logged here with the raw fragment.
CREATE TABLE IF NOT EXISTS parse_failures (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module        text NOT NULL,
    source_url    text,
    field_name    text,
    raw_fragment  text,
    reason        text,
    created_at    text NOT NULL
);

-- Anything that requires human judgement before it can be promoted into a
-- canonical table (unmatched buyer names, unverified CDP/committee document
-- candidates, charities whose accounts don't parse cleanly, etc).
CREATE TABLE IF NOT EXISTS review_queue (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module         text NOT NULL,
    item_type      text NOT NULL,
    raw_value      text NOT NULL,
    context_json   text,
    status         text NOT NULL DEFAULT 'pending',
    created_at     text NOT NULL,
    resolved_at    text
);

-- Constraint 5: idempotent and resumable. Each module persists a cursor
-- (e.g. last publication date processed) so an interrupted run resumes.
CREATE TABLE IF NOT EXISTS module_cursors (
    module        text PRIMARY KEY,
    cursor_value  text,
    updated_at    text NOT NULL
);

-- Constraint 4: conditional requests on re-runs. Keyed by URL so http.py can
-- send If-None-Match / If-Modified-Since without re-fetching unchanged docs.
CREATE TABLE IF NOT EXISTS http_cache (
    url            text PRIMARY KEY,
    host           text NOT NULL,
    etag           text,
    last_modified  text,
    payload_sha256 text,
    updated_at     text NOT NULL
);
