-- What the server has been asked to run, kept where a restart cannot lose it.
--
-- The job registry (pipeline/web/jobs.py) is in memory, and that was the right
-- call for the thing it was built for: a job is something you *watch*, and a
-- server restart is the end of watching. But it also made the registry the
-- only record that a run had happened at all. Close the server and the fact
-- that a four-hour crawl ran last night, with what arguments, and whether it
-- finished, is gone -- the evidence it collected is in the warehouse and the
-- lines it printed are in logs/, but nothing joins the two.
--
-- So the *fact* of a job is persisted here and its log is not. The log lines
-- already have a home, and copying thousands of them into the warehouse would
-- put the chattiest table in the database next to the evidence it is not.
--
-- `dry_run` is a column rather than something to dig out of args_json,
-- because "did this run write anything?" is the first question anyone asks of
-- a job list and it should not require parsing JSON to answer.
--
-- PostgreSQL dialect of ../0029_job_runs.sql.
--
CREATE TABLE IF NOT EXISTS job_runs (
    -- The registry allocates these, continuing from the highest persisted id
    -- on startup so that a job id means one job for the life of the warehouse
    -- rather than for the life of a process.
    --
    -- `GENERATED BY DEFAULT` rather than a bare `bigint` is what makes this
    -- the same column as SQLite's `INTEGER PRIMARY KEY`: an explicit id is
    -- accepted, which is what the registry always sends, and an omitted one
    -- is assigned rather than rejected. A bare `bigint PRIMARY KEY` would
    -- turn "the registry forgot to allocate" from a silently-recovered case
    -- into a NOT NULL violation, which is a behaviour change and this phase
    -- is not making any.
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          text NOT NULL,
    label         text NOT NULL,
    args_json     text NOT NULL,
    -- 'interrupted' is what a process that died mid-run leaves behind. It is
    -- written on startup, not by the job: a job that could still update its
    -- own row would not have been interrupted.
    state         text NOT NULL CHECK (state IN ('running', 'finished', 'failed', 'interrupted')),
    dry_run       bigint NOT NULL DEFAULT 0,
    started_at    text NOT NULL,
    finished_at   text,
    error         text,
    summary_json  text
);

-- The job list is "newest first, a page of them", and nothing else.
--
-- `NULLS LAST` is explicit because it is not the same default on both
-- engines: SQLite puts NULLs last in a DESC index, PostgreSQL puts them
-- first. `started_at` is NOT NULL so nothing turns on it today, and it is
-- written down so that a future nullable sort column does not inherit a
-- silent difference.
CREATE INDEX IF NOT EXISTS idx_job_runs_started_at
    ON job_runs (started_at DESC NULLS LAST);
