-- Who turned a candidate into evidence, and on what.
--
-- Three modules discover candidates -- m09 (CDP documents), m10 (committee
-- papers), m15 (FOI requests) -- and none of them promotes one. That is the
-- correct default and it stays: `match_quality` is ModernGov's own ranking,
-- `confidence` counts matching signals, and neither is this pipeline's
-- judgement that a document is what its link text claims. So promotion is a
-- human act, and this is where the act is recorded.
--
-- 1,941 candidates and zero promoted rows is what prompted it. The evidence
-- was being collected and then not crossing into the evidence base, because
-- the only documented way across was hand-written SQL.
--
-- Two things this table is NOT:
--
--   * It is not `review_decisions`. That records judgements on review_queue
--     items -- "this buyer name is unmatched", "these concerns are PDF-only"
--     -- which are questions about the pipeline's own gaps. A promotion is a
--     statement about the world: this URL is a Combating Drugs Partnership
--     strategy for this authority. Different question, different evidence
--     threshold, different table.
--
--   * It is not a copy of the candidate. The candidate's provenance describes
--     the *listing page the link was found on*. An evidence row carrying that
--     hash would be claiming the document was fetched when it was not, which
--     is the one thing this project does not do. Promotion fetches the
--     document itself, and the provenance recorded here and on the evidence
--     row is that fetch.
--
-- The guarantee is structural, not conventional: the triggers below refuse an
-- insert into any of the three evidence tables that has no promotion row.
-- Nothing reaches them by another route -- not a module, not the SQL box, not
-- a future author who has not read this file.
--
-- PostgreSQL dialect of ../0030_evidence_promotions.sql. See README.md in this directory for
-- the conversion rules; the porting decisions specific to this file are
-- commented where they occur.
--
CREATE TABLE IF NOT EXISTS evidence_promotions (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_table   text NOT NULL,
    -- How the candidate is identified in its own table. URL rather than
    -- rowid: rowids are not stable across a rebuild, and the URL is what a
    -- person was actually looking at.
    candidate_url     text NOT NULL,
    target_table      text NOT NULL,
    -- The evidence row's natural key, as "<authority>|<url>", which is what
    -- the triggers match on.
    target_key        text NOT NULL,
    -- Never defaulted. The UI asks who is promoting and sends it, the same
    -- rule review_decisions has: an audit row whose author is a guess is
    -- worse than no audit row.
    promoted_by       text NOT NULL,
    promoted_at       text NOT NULL,
    note              text,
    -- The candidate as it read when the judgement was taken. A later module
    -- run can refresh a candidate row underneath a decision already made
    -- against the old text.
    candidate_context_json text NOT NULL,
    -- Provenance of the fetch that produced the evidence row.
    fetched_url       text,
    http_status       bigint,
    payload_sha256    text,
    archived_path     text
);

-- The triggers below do an EXISTS on (target_table, target_key) for every
-- insert into an evidence table, so it is on the write path rather than a
-- reporting convenience.
CREATE INDEX IF NOT EXISTS idx_evidence_promotions_target
    ON evidence_promotions (target_table, target_key);

CREATE INDEX IF NOT EXISTS idx_evidence_promotions_candidate
    ON evidence_promotions (candidate_table, candidate_url);

-- "What has been promoted lately", and by whom.
CREATE INDEX IF NOT EXISTS idx_evidence_promotions_promoted_at
    ON evidence_promotions (promoted_at DESC);

-- The three refusals.
--
-- Written per table rather than generated, because a trigger naming its own
-- table and key is readable at the point someone hits it, and there are only
-- three of them. Each fires BEFORE INSERT, so the row never lands.
--
-- PORTING NOTE. SQLite's `WHEN <condition> ... SELECT RAISE(ABORT, msg)`
-- becomes a plpgsql function plus a trigger that calls it. Three things about
-- the port are deliberate:
--
--   * The `WHEN` clause moves *inside* the function body rather than staying
--     on the trigger. PostgreSQL allows a `WHEN` on a trigger, but it may not
--     contain a subquery, and every one of these conditions is a `NOT EXISTS`.
--
--   * `USING ERRCODE = 'integrity_constraint_violation'`. A bare
--     `RAISE EXCEPTION` arrives in Python as `psycopg.errors.RaiseException`,
--     which descends from `DatabaseError` and NOT from `IntegrityError` — so
--     the promotion suite's assertion, and every call site that catches an
--     integrity error to turn a refusal into a message rather than a
--     traceback, would stop matching. The errcode puts it in the same class
--     SQLite's `RAISE(ABORT, …)` lands in. It is also the honest
--     classification: this is a constraint that spans two tables and so
--     cannot be written as a CHECK.
--
--   * The message text is identical to the SQLite one, character for
--     character. It is what an operator reads, and it names the file to go
--     and read next.
--
-- The functions return NEW because a BEFORE INSERT trigger that returns NULL
-- silently skips the row — which would turn a refusal into an insert that
-- quietly did nothing, the exact failure this mechanism exists to prevent.

CREATE OR REPLACE FUNCTION cdp_documents_need_a_promotion()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM evidence_promotions
        WHERE target_table = 'cdp_documents'
          AND target_key = NEW.authority_ons_code || '|' || NEW.document_url
    ) THEN
        RAISE EXCEPTION 'cdp_documents: nothing is promoted without a human — record an evidence_promotions row first, via pipeline/promote.py'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER cdp_documents_need_a_promotion
BEFORE INSERT ON cdp_documents
FOR EACH ROW
EXECUTE FUNCTION cdp_documents_need_a_promotion();

CREATE OR REPLACE FUNCTION committee_papers_need_a_promotion()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM evidence_promotions
        WHERE target_table = 'committee_papers'
          AND target_key = NEW.authority_ons_code || '|' || NEW.document_url
    ) THEN
        RAISE EXCEPTION 'committee_papers: nothing is promoted without a human — record an evidence_promotions row first, via pipeline/promote.py'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER committee_papers_need_a_promotion
BEFORE INSERT ON committee_papers
FOR EACH ROW
EXECUTE FUNCTION committee_papers_need_a_promotion();

CREATE OR REPLACE FUNCTION foi_requests_need_a_promotion()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM evidence_promotions
        WHERE target_table = 'foi_requests'
          AND target_key = NEW.ons_code || '|' || NEW.request_url
    ) THEN
        RAISE EXCEPTION 'foi_requests: nothing is promoted without a human — record an evidence_promotions row first, via pipeline/promote.py'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER foi_requests_need_a_promotion
BEFORE INSERT ON foi_requests
FOR EACH ROW
EXECUTE FUNCTION foi_requests_need_a_promotion();
