-- Who checked a workforce census figure against its source, and against what.
--
-- 68 metrics sat at `verified = 0` from the day m06 first ran, and the portal
-- correctly showed every one of them as awaiting verification. Not for want of
-- a decision about any individual figure -- for want of anywhere to record the
-- decision. The only documented route was a hand-run
--
--     UPDATE workforce_census_metrics SET verified = 1 WHERE census_year = ?;
--
-- printed into a generated markdown worklist, which sets 20-odd flags on one
-- statement, attributes them to nobody, and leaves no record that anyone read
-- a page. This file replaces that route and refuses it.
--
-- WHY THIS IS NOT A FOURTH `KINDS` ENTRY IN pipeline/promote.py
--
-- Promotion and census verification look like the same act and are not, in
-- three ways that each break the shared table:
--
--   * A promotion *creates* an evidence row in another table from a candidate
--     row. A census verification raises a flag on a row that already exists
--     and already carries full provenance -- the report was fetched, hashed and
--     archived by m06, and every metric row carries that fetch. There is no
--     candidate and no target.
--
--   * `evidence_promotions` records a fetch: fetched_url, http_status,
--     payload_sha256, archived_path. Nothing is fetched here, and there must
--     be no column tempting anybody to fill those in. What this table records
--     instead is which already-archived bytes were read -- named
--     `checked_against_*` so that the hash is never mistaken for the hash of a
--     retrieval this act performed. It performed none.
--
--   * A census metric has no URL and no authority, so it has no
--     `<authority>|<url>` target_key. Its identity is four columns, one of
--     which is a whole verbatim line of PDF text. Concatenating that into a
--     key string to fit a column built for something else is the pretence this
--     project does not make.
--
-- So: a sibling table with its own trigger, the same shape 0030 gave
-- promotions and 0026 gave review decisions. Different question, different
-- evidence threshold, different table.
--
-- The guarantee is structural, not conventional: the triggers at the bottom
-- refuse `verified = 1` on a metric with no decision row behind it, whether
-- the write comes from this module, from a module re-run, from the SQL box, or
-- from an author who has not read this file.
--
-- PostgreSQL dialect of ../0033_census_verifications.sql. See README.md in this directory for
-- the conversion rules; the porting decisions specific to this file are
-- commented where they occur.
--
CREATE TABLE IF NOT EXISTS census_verifications (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The metric's natural key, in full and unhashed. Stored as its four
    -- columns rather than as a digest so that this table joins to
    -- workforce_census_metrics and reads without a lookup: the audit trail is
    -- for a person six months from now, and "which figure was this?" must be
    -- answerable from the row.
    census_year            bigint NOT NULL,
    metric                  text NOT NULL,
    workforce_segment        text NOT NULL,
    raw_text                  text NOT NULL,

    -- 'verified' means the figure was checked against the source line and is
    -- right. 'rejected' means it was checked and the parse is wrong. Both are
    -- somebody having looked; a metric with neither is a metric nobody has
    -- read, and keeping those distinguishable is the whole point (see D-04,
    -- where a queue of answered-but-still-pending items trained its operator
    -- to ignore the queue).
    decision                   text NOT NULL
        CHECK (decision IN ('verified', 'rejected')),

    -- Never defaulted, the same rule review_decisions and evidence_promotions
    -- have: an audit row whose author is a guess is worse than no audit row.
    decided_by                  text NOT NULL,
    decided_at                   text NOT NULL,
    note                          text,

    -- The figure as it read when the judgement was taken. A later parser
    -- revision can change the value under a decision already made, and
    -- `census_verify.stale()` is the query that finds it. Without these three
    -- columns that query cannot exist and a verification silently comes to
    -- vouch for a number nobody checked.
    checked_value                  double precision,
    checked_unit                    text,
    checked_page                     bigint,

    -- What it was checked *against*: the report m06 already fetched, named by
    -- the hash of the bytes m06 read. Not a fetch of this act's own -- see the
    -- header. If the publisher reissues the PDF under the same URL, this hash
    -- stops matching the metric row's and the verification is stale, which is
    -- the second half of what `stale()` reports.
    checked_against_url              text,
    checked_against_sha256            text
);

-- The triggers below do an EXISTS on the four key columns for every write that
-- raises a flag, so this index is on the write path rather than a reporting
-- convenience.
CREATE INDEX IF NOT EXISTS idx_census_verifications_metric
    ON census_verifications (census_year, metric, workforce_segment);

CREATE INDEX IF NOT EXISTS idx_census_verifications_decided_at
    ON census_verifications (decided_at DESC);

-- `verified_at` and `rejected`, so that a census metric carries the same three
-- decision columns every candidate table does. That matters for one specific
-- reason beyond symmetry: `db.DECISION_COLUMNS` names all three, and m06
-- passes it as `preserve`, so a re-run of the module cannot reset a decision
-- once the columns exist. Before this migration two of the three did not, and
-- `preserve` was protecting one column out of three by accident.
--
-- No IF NOT EXISTS on ADD COLUMN -- SQLite has none, and the migration runner
-- applies each file once and records it.
ALTER TABLE workforce_census_metrics ADD COLUMN verified_at text;
ALTER TABLE workforce_census_metrics ADD COLUMN rejected bigint NOT NULL DEFAULT 0;

-- The two refusals.
--
-- Two, not one, because a flag can be raised by an UPDATE on an existing row
-- or carried in on an INSERT, and a rule enforced on one route is not enforced.
-- The UPDATE trigger fires on `verified` being named, so the WHEN clause reads
-- OLD as well as NEW: re-writing a row that is already verified is not a new
-- decision and must not need a second one.
-- See the porting note in 0030 for why the WHEN clause moves inside the
-- function body and why these raise with an explicit ERRCODE.
--
-- One difference from 0030 worth naming: `BEFORE UPDATE OF verified` keeps
-- its column list on the trigger, where PostgreSQL supports it exactly as
-- SQLite does. Only the subquery half of the condition had to move.

CREATE OR REPLACE FUNCTION census_metric_verify_needs_a_decision()
RETURNS trigger AS $$
BEGIN
    IF NEW.verified = 1 AND COALESCE(OLD.verified, 0) = 0 AND NOT EXISTS (
        SELECT 1 FROM census_verifications
        WHERE census_year = NEW.census_year
          AND metric = NEW.metric
          AND workforce_segment = NEW.workforce_segment
          AND raw_text = NEW.raw_text
          AND decision = 'verified'
    ) THEN
        RAISE EXCEPTION 'workforce_census_metrics: a census figure is not verified without a human — record a census_verifications row first, via pipeline/census_verify.py or the Census tab. The bulk UPDATE the old worklist printed is what this refuses.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER census_metric_verify_needs_a_decision
BEFORE UPDATE OF verified ON workforce_census_metrics
FOR EACH ROW
EXECUTE FUNCTION census_metric_verify_needs_a_decision();

CREATE OR REPLACE FUNCTION census_metric_insert_needs_a_decision()
RETURNS trigger AS $$
BEGIN
    IF NEW.verified = 1 AND NOT EXISTS (
        SELECT 1 FROM census_verifications
        WHERE census_year = NEW.census_year
          AND metric = NEW.metric
          AND workforce_segment = NEW.workforce_segment
          AND raw_text = NEW.raw_text
          AND decision = 'verified'
    ) THEN
        RAISE EXCEPTION 'workforce_census_metrics: a census figure is not verified without a human — record a census_verifications row first, via pipeline/census_verify.py or the Census tab.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER census_metric_insert_needs_a_decision
BEFORE INSERT ON workforce_census_metrics
FOR EACH ROW
EXECUTE FUNCTION census_metric_insert_needs_a_decision();
