-- PostgreSQL dialect of ../0050_evidence_graph.sql.
-- The tables make PostgreSQL authoritative for the derived graph's identity,
-- evidence lineage, projection queue/runs and reproducible analytical output.

CREATE TABLE IF NOT EXISTS entities (
    entity_id                 text PRIMARY KEY,
    entity_type               text NOT NULL,
    canonical_name            text NOT NULL,
    canonical_name_normalized text NOT NULL,
    status                    text NOT NULL DEFAULT 'active',
    created_at                text NOT NULL,
    updated_at                text NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_entities_type_name
    ON entities (entity_type, canonical_name_normalized);

CREATE TABLE IF NOT EXISTS entity_aliases (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id          text NOT NULL REFERENCES entities(entity_id),
    alias              text NOT NULL,
    alias_normalized   text NOT NULL,
    alias_type         text NOT NULL DEFAULT 'known_as',
    source_evidence_id text,
    confidence         double precision,
    valid_from         text,
    valid_to           text,
    created_at         text NOT NULL,
    UNIQUE (entity_id, alias_normalized, alias_type)
);

CREATE INDEX IF NOT EXISTS idx_entity_aliases_normalized
    ON entity_aliases (alias_normalized);

CREATE TABLE IF NOT EXISTS entity_identifiers (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id          text NOT NULL REFERENCES entities(entity_id),
    identifier_scheme  text NOT NULL,
    identifier_value   text NOT NULL,
    valid_from         text,
    valid_to           text,
    source_evidence_id text,
    created_at         text NOT NULL,
    UNIQUE (identifier_scheme, identifier_value)
);

CREATE TABLE IF NOT EXISTS evidence_records (
    evidence_id     text PRIMARY KEY,
    source_system   text NOT NULL,
    source_url      text,
    retrieved_at    text NOT NULL,
    http_status     bigint,
    payload_sha256  text NOT NULL,
    raw_object_path text,
    mime_type       text,
    content_length  bigint,
    created_at      text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_evidence_records_payload
    ON evidence_records (payload_sha256);

CREATE TABLE IF NOT EXISTS graph_claims (
    claim_id           text PRIMARY KEY,
    source_claim_id    text,
    subject_entity_id  text REFERENCES entities(entity_id),
    predicate          text NOT NULL,
    object_entity_id   text REFERENCES entities(entity_id),
    object_literal     text,
    claim_text         text,
    evidence_id        text REFERENCES evidence_records(evidence_id),
    document_reference text,
    page_number        bigint,
    section            text,
    text_start         bigint,
    text_end           bigint,
    evidence_span      text,
    extraction_method  text NOT NULL,
    extractor_name     text,
    extractor_version  text,
    confidence         double precision,
    review_status      text NOT NULL DEFAULT 'draft',
    created_at         text NOT NULL,
    CHECK (object_entity_id IS NOT NULL OR object_literal IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_graph_claims_subject ON graph_claims (subject_entity_id);
CREATE INDEX IF NOT EXISTS idx_graph_claims_evidence ON graph_claims (evidence_id);

CREATE TABLE IF NOT EXISTS entity_relationships (
    relationship_id    text PRIMARY KEY,
    subject_entity_id  text NOT NULL REFERENCES entities(entity_id),
    predicate          text NOT NULL,
    object_entity_id   text NOT NULL REFERENCES entities(entity_id),
    relationship_type  text NOT NULL,
    evidence_id        text REFERENCES evidence_records(evidence_id),
    claim_id           text REFERENCES graph_claims(claim_id),
    valid_from         text,
    valid_to           text,
    confidence         double precision,
    derivation_type    text NOT NULL,
    derivation_version text,
    created_at         text NOT NULL,
    updated_at         text NOT NULL,
    CHECK (derivation_type IN ('SOURCE_FACT', 'EXTRACTED_CLAIM',
                               'DERIVED_RELATIONSHIP', 'ANALYTICAL_SIGNAL'))
);

CREATE INDEX IF NOT EXISTS idx_entity_relationships_subject
    ON entity_relationships (subject_entity_id, predicate);
CREATE INDEX IF NOT EXISTS idx_entity_relationships_object
    ON entity_relationships (object_entity_id, predicate);

CREATE TABLE IF NOT EXISTS graph_projection_queue (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_type   text NOT NULL,
    object_id     text NOT NULL,
    operation     text NOT NULL,
    created_at    text NOT NULL,
    processed_at  text,
    attempt_count bigint NOT NULL DEFAULT 0,
    last_error    text,
    UNIQUE (object_type, object_id, operation, processed_at)
);

CREATE INDEX IF NOT EXISTS idx_graph_projection_queue_pending
    ON graph_projection_queue (processed_at, id);

CREATE TABLE IF NOT EXISTS graph_projection_runs (
    run_id             text PRIMARY KEY,
    started_at         text NOT NULL,
    completed_at       text,
    status             text NOT NULL,
    schema_version     text NOT NULL,
    projector_version  text NOT NULL,
    warehouse_snapshot text,
    entity_count       bigint NOT NULL DEFAULT 0,
    relationship_count bigint NOT NULL DEFAULT 0,
    claim_count        bigint NOT NULL DEFAULT 0,
    error_count        bigint NOT NULL DEFAULT 0,
    error_detail       text
);

CREATE TABLE IF NOT EXISTS graph_metrics (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id        text REFERENCES entities(entity_id),
    metric_name      text NOT NULL,
    metric_value     double precision NOT NULL,
    analysis_name    text NOT NULL,
    analysis_version text NOT NULL,
    graph_snapshot   text NOT NULL,
    calculated_at    text NOT NULL,
    parameters_json  text NOT NULL,
    UNIQUE (entity_id, metric_name, analysis_name, analysis_version, graph_snapshot)
);
