-- Semantic-analysis layer (pipeline/nlp), tranche 034F: machine claim
-- candidates.
--
-- PostgreSQL dialect of ../0068_document_claim_candidates.sql. See README.md
-- in this directory for the conversion rules. TEXT -> text, INTEGER ->
-- bigint, REAL -> double precision, INTEGER PRIMARY KEY AUTOINCREMENT ->
-- bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY.
--
-- relation_score ranks candidates for a reviewer, it is NOT P(the claim is
-- true) and is never multiplied into a figure. Nothing here is auto-promoted:
-- a separate policy queues a slice into review_queue, and only a person's
-- decision produces a graph_claims draft.

CREATE TABLE IF NOT EXISTS document_claim_candidates (
    claim_candidate_id         text PRIMARY KEY,
    document_chunk_id          text NOT NULL REFERENCES document_chunks(document_chunk_id),
    subject_mention_id         text REFERENCES document_concept_mentions(document_concept_mention_id),
    subject_hint               text,
    predicate                  text NOT NULL,
    object_concept_id          text,
    object_literal             text,
    assertion_status           text NOT NULL,
    relation_extractor         text NOT NULL,
    relation_extractor_version text NOT NULL,
    relation_score             double precision,
    evidence_span              text NOT NULL,
    char_start                 bigint NOT NULL,
    char_end                   bigint NOT NULL,
    status                     text NOT NULL DEFAULT 'new',
    superseded                 bigint NOT NULL DEFAULT 0,
    nlp_run_id                 text REFERENCES nlp_runs(run_id),
    created_at                 text NOT NULL,
    UNIQUE (document_chunk_id, relation_extractor, relation_extractor_version, char_start, char_end, predicate, subject_mention_id, object_concept_id, object_literal)
);

CREATE INDEX IF NOT EXISTS idx_claim_candidates_status
    ON document_claim_candidates (status) WHERE superseded = 0;
CREATE INDEX IF NOT EXISTS idx_claim_candidates_predicate
    ON document_claim_candidates (predicate, assertion_status);
CREATE INDEX IF NOT EXISTS idx_claim_candidates_chunk
    ON document_claim_candidates (document_chunk_id);

CREATE TABLE IF NOT EXISTS claim_candidate_decisions (
    id                           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_candidate_id           text NOT NULL REFERENCES document_claim_candidates(claim_candidate_id),
    review_queue_id              bigint REFERENCES review_queue(id),
    decision                     text NOT NULL,
    decided_by                   text NOT NULL,
    reason_code                  text,
    corrected_subject_mention_id text REFERENCES document_concept_mentions(document_concept_mention_id),
    corrected_predicate          text,
    corrected_object_concept_id  text,
    corrected_object_literal     text,
    graph_claim_id               text REFERENCES graph_claims(claim_id),
    note                         text,
    decided_at                   text NOT NULL,
    UNIQUE (claim_candidate_id, decided_by, decided_at)
);

CREATE INDEX IF NOT EXISTS idx_claim_candidate_decisions_candidate
    ON claim_candidate_decisions (claim_candidate_id);
