-- Phase 3: durable, versioned incremental NLP state.
--
-- A row describes the latest successful interpretation of one stable input.
-- Output tables remain the canonical findings; this ledger answers whether a
-- stage may safely skip an input and why it must be invalidated.

CREATE TABLE IF NOT EXISTS nlp_stage_state (
    stage                       text NOT NULL,
    input_identity              text NOT NULL,
    input_hash                  text NOT NULL,
    processor_version           text NOT NULL,
    model_or_ontology_version   text,
    configuration_hash          text NOT NULL,
    dependency_hash             text NOT NULL,
    output_digest               text,
    status                      text NOT NULL,
    last_run_id                 text REFERENCES nlp_runs(run_id),
    updated_at                  timestamptz NOT NULL,
    PRIMARY KEY (stage, input_identity),
    CHECK (stage IN ('chunking','labels','spans','context','relations','resolution','embeddings')),
    CHECK (status IN ('pending','running','complete','failed','invalidated'))
);

CREATE INDEX IF NOT EXISTS idx_nlp_stage_state_pending
    ON nlp_stage_state (stage, status, input_identity);

CREATE TABLE IF NOT EXISTS nlp_stage_checkpoints (
    run_id              text NOT NULL REFERENCES nlp_runs(run_id),
    stage               text NOT NULL,
    batch_ordinal       bigint NOT NULL,
    last_input_identity text NOT NULL,
    rows_processed      bigint NOT NULL,
    rows_written        bigint NOT NULL,
    committed_at        timestamptz NOT NULL,
    PRIMARY KEY (run_id, batch_ordinal)
);

CREATE TABLE IF NOT EXISTS nlp_stage_failures (
    failure_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              text REFERENCES nlp_runs(run_id),
    stage               text NOT NULL,
    input_identity      text NOT NULL,
    input_hash          text NOT NULL,
    failure_class       text NOT NULL,
    error_detail        text NOT NULL,
    failed_at           timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_nlp_stage_failures_input
    ON nlp_stage_failures (stage, input_identity, failed_at DESC);
