-- Centrally reserved migration 0103, reconciled against beta before use.
--
-- Two gaps performance.md's Phase 4 named and nothing in the schema closed:
--
-- 1. Nothing distinguished "a source was searched and had nothing" from "a
--    source was never searched, was unavailable, or failed" -- coverage was
--    inferred purely from a row's presence in an evidence table. That makes
--    absence indistinguishable from non-existence, which is exactly what
--    docs/CAVEATS.md forbids concluding. collection_attempts is the record
--    of the attempt itself, independent of what it found.
--
-- 2. review_queue and parse_failures already carry two of "quarantine's"
--    concerns (a link needing a human judgement call; a field that would not
--    parse) and are left exactly as they are -- both work, and 75+ call
--    sites rely on their current shape. But three other categories
--    performance.md names -- a rejected candidate, a failed stage input, an
--    archive object whose hash no longer matches -- had no durable, listable,
--    retryable home at all. quarantine_items is that home, additive rather
--    than a migration of the other two tables' data.
--
-- Native timestamptz/jsonb, matching 0102's dialect rather than the older
-- text-everywhere tables: this is the newer sibling in the same reserved
-- trio and 0099 (still unwritten) is expected to bring the rest forward.
--
-- `run_id` is a plain text column, not `REFERENCES run_ledger(run_id)`,
-- matching run_ledger's own `parent_run_id` (migration 0073): a run-ledger
-- write is documented there as best-effort ("must not fail the collection"),
-- and `run_ledger.start()` returns `None` rather than raise on failure. A
-- hard FK would make every collection attempt and quarantined item depend on
-- run_ledger succeeding and existing, which is the opposite of best-effort,
-- and would block dropping run_ledger at all -- exactly what
-- tests/test_run_ledger.py and tests/test_web_degradation.py's graceful-
-- degradation tests do to prove the collection survives without it.

CREATE TABLE IF NOT EXISTS collection_attempts (
    attempt_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module          text NOT NULL,
    run_id          text,
    source_system   text NOT NULL,
    scope           text NOT NULL,
    started_at      timestamptz NOT NULL,
    finished_at     timestamptz,
    status          text NOT NULL DEFAULT 'running',
    failure_class   text,
    result_count    integer,
    coverage_state  text,
    detail_json     jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (status IN ('running', 'ok', 'failed', 'empty')),
    CHECK (coverage_state IS NULL OR coverage_state IN
           ('covered', 'no_results', 'unavailable', 'failed', 'skipped')),
    CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX IF NOT EXISTS idx_collection_attempts_module_source
    ON collection_attempts (module, source_system, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_collection_attempts_run
    ON collection_attempts (run_id);

-- No natural-key uniqueness here, deliberately: two attempts against the
-- same (module, source_system, scope) in the same run are two different
-- events (a page walk that legitimately repeats a scope on retry), not
-- duplicates to collapse the way parse_failures collapses re-observed
-- fields. The row is the attempt, not a fact about the world.

CREATE TABLE IF NOT EXISTS quarantine_items (
    item_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind            text NOT NULL,
    module          text NOT NULL,
    run_id          text,
    stage           text,
    item_identity   text NOT NULL,
    failure_class   text NOT NULL,
    reason          text NOT NULL,
    input_sha256    text,
    output_sha256   text,
    payload_json    jsonb NOT NULL DEFAULT '{}'::jsonb,
    first_seen_at   timestamptz NOT NULL,
    last_seen_at    timestamptz NOT NULL,
    retry_count     integer NOT NULL DEFAULT 0,
    retry_state     text NOT NULL DEFAULT 'pending',
    resolved_at     timestamptz,
    CHECK (kind IN ('rejected_candidate', 'failed_stage_input', 'archive_mismatch')),
    CHECK (retry_state IN ('pending', 'retrying', 'resolved', 'irreducible'))
);

-- Idempotent re-observation, the same idiom as parse_failures (migration
-- 0007): re-running whatever found this item updates last_seen_at/reason
-- rather than appending another copy, so "how many are still unresolved?"
-- stays answerable across repeated runs.
CREATE UNIQUE INDEX IF NOT EXISTS idx_quarantine_items_natural
    ON quarantine_items (kind, module, item_identity);
CREATE INDEX IF NOT EXISTS idx_quarantine_items_retry_state
    ON quarantine_items (retry_state, kind, module);
