-- The portal's contract list, in the order it asks for it.
--
-- `ORDER BY date_published DESC, notice_id` is how every contracts query in
-- pipeline/web/public_queries.py ends, because it is how the page reads:
-- newest first. Until now nothing indexed it, so answering the first page of
-- 98,636 notices meant reading the whole table and sorting it -- 83ms on
-- PostgreSQL over 14,728 buffers, and 6 seconds on SQLite, which is where the
-- Phase 3 baseline found the portal's slowest page.
--
-- Measured before it was added, which is the rule this project applies to
-- indexes (see docs/benchmarks/README.md and the comments in 0026 and 0033):
-- built in a transaction that was then rolled back, the same query planned as
-- an index scan of 128 buffers and ran in 1.9ms. Forty-four times, for 4 MB
-- against a 114 MB table.
--
-- The write cost is one more B-tree on m01's inserts, which is the reason not
-- to add indexes speculatively. It is paid here because this is the portal's
-- front page rather than a panel someone opens occasionally, and because the
-- sort it replaces is the largest single cost in the baseline.
--
-- `notice_id` is in the key, not decoration: it is the tie-break the queries
-- already sort on, and without it the index answers the first column and
-- leaves the sort to be finished by hand.
--
-- On NULLs. SQLite's DESC index puts them last, which is also where SQLite's
-- `ORDER BY ... DESC` puts them, so the two agree here without saying so. The
-- PostgreSQL file says `NULLS LAST` explicitly, because PostgreSQL's defaults
-- disagree on both counts and the point of the pair is that a reader sees the
-- same page whichever backend answered. `date_published` holds no NULLs
-- today; that is a fact about the data, not a guarantee from the schema.
CREATE INDEX IF NOT EXISTS idx_contracts_date_published
    ON contracts (date_published DESC, notice_id);
