"""The review UI: what it may read, what it may write, and what it refuses.

The interesting assertions here are the negative ones. A tool that shows the
warehouse in a browser and writes decisions back is the first thing in this
pipeline that can damage the evidence base by accident, so the tests that
matter most are the ones fixing what it *cannot* do: write through the
browsing connection, resurrect a decided item's context on the next run, hand
out personal data without being asked twice, or take a write from another
origin.
"""
from __future__ import annotations

import json
import threading

import httpx
import pytest

from pipeline import db
from pipeline.web import queries, review
from pipeline.web.server import build_server, local_addresses, reachable_urls


@pytest.fixture
def seeded(conn: db.Connection) -> db.Connection:
    """A warehouse with a few review items and a restricted table."""
    db.record_review_item(conn, "m01_procurement", "unmatched_buyer_name",
                           "Barsetshire County Council", json.dumps({"contracts": 3}))
    db.record_review_item(conn, "m01_procurement", "unmatched_buyer_name", "Ambridge BC")
    db.record_review_item(conn, "m04_companies", "possible_group_company", "12345678",
                           json.dumps({"name": "Example Care Ltd"}))
    db.record_parse_failure(conn, "m03_charity_finance", "wages", "£not-a-number",
                             "could not parse currency amount")
    conn.execute("CREATE TABLE restricted_people ("
                  "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                  "name TEXT)")
    conn.execute("INSERT INTO restricted_people (name) VALUES ('A Person')")
    conn.commit()
    return conn


def ids_for(conn: db.Connection, raw_value: str) -> int:
    return conn.execute(
        "SELECT id FROM review_queue WHERE raw_value = ?", (raw_value,)).fetchone()["id"]


# --- the browsing connection cannot write ------------------------------------


def test_browsing_connection_refuses_writes(seeded, settings):
    """mode=ro is the guard, not SQL inspection: a write is refused by the
    driver regardless of how it is phrased."""
    ro = queries.readonly_connection(settings)
    with pytest.raises(db.OperationalError, match="read.?only"):
        ro.execute("DELETE FROM review_queue")
    with pytest.raises(db.OperationalError, match="read.?only"):
        ro.execute("UPDATE review_queue SET status = 'approved'")
    ro.close()


def test_sql_box_reports_a_write_attempt_rather_than_performing_it(seeded, settings):
    ro = queries.readonly_connection(settings)
    with pytest.raises(queries.QueryError):
        queries.run_select(ro, "DELETE FROM review_queue")
    ro.close()
    assert seeded.execute("SELECT COUNT(*) FROM review_queue").fetchone()[0] == 3


def test_sql_box_refuses_more_than_one_statement(seeded, settings):
    ro = queries.readonly_connection(settings)
    with pytest.raises(queries.QueryError):
        queries.run_select(ro, "SELECT 1; SELECT 2")
    ro.close()


def test_sql_box_caps_the_number_of_rows_returned(seeded, settings):
    ro = queries.readonly_connection(settings)
    result = queries.run_select(
        ro,
        "WITH RECURSIVE n(i) AS (SELECT 1 UNION ALL SELECT i + 1 FROM n WHERE i < 100) SELECT i FROM n",
        limit=10,
    )
    assert len(result["rows"]) == 10
    assert result["truncated"] is True
    ro.close()


def test_missing_warehouse_is_a_message_not_a_traceback(settings):
    settings.database_url = ""
    settings.database_ro_url = ""
    with pytest.raises(queries.QueryError, match="No DATABASE_URL"):
        queries.readonly_connection(settings)


# --- browsing ----------------------------------------------------------------


def test_list_objects_counts_tables_and_flags_restricted(seeded, settings):
    ro = queries.readonly_connection(settings)
    objects = {o["name"]: o for o in queries.list_objects(ro)}
    ro.close()

    assert objects["review_queue"]["rows"] == 3
    assert objects["review_queue"]["restricted"] is False
    assert objects["restricted_people"]["restricted"] is True
    assert "sqlite_sequence" not in objects


def test_read_table_pages_searches_and_sorts(seeded, settings):
    ro = queries.readonly_connection(settings)

    page = queries.read_table(ro, "review_queue", limit=2, offset=0)
    assert page["total"] == 3
    assert len(page["rows"]) == 2
    assert page["ordered"] is True

    found = queries.read_table(ro, "review_queue", search="Ambridge")
    assert found["total"] == 1

    # LIKE wildcards in the term are the user's literal text, not a pattern.
    assert queries.read_table(ro, "review_queue", search="%")["total"] == 0

    ordered = queries.read_table(ro, "review_queue", order_by="raw_value", descending=True)
    values = [row[3] for row in ordered["rows"]]
    assert values == sorted(values, reverse=True)
    ro.close()


def test_read_table_rejects_an_unknown_object(seeded, settings):
    ro = queries.readonly_connection(settings)
    with pytest.raises(queries.QueryError, match="No table or view"):
        queries.read_table(ro, "review_queue; DROP TABLE review_queue")
    ro.close()


# --- deciding ----------------------------------------------------------------


def test_approving_sets_status_and_records_who_decided(seeded):
    item_id = ids_for(seeded, "Ambridge BC")
    result = review.decide(seeded, [item_id], "approved", decided_by="Jon", note="confirmed by hand")

    assert result["updated"] == [item_id]
    row = seeded.execute("SELECT * FROM review_queue WHERE id = ?", (item_id,)).fetchone()
    assert row["status"] == "approved"
    assert row["resolved_at"] is not None

    decision = seeded.execute(
        "SELECT * FROM review_decisions WHERE review_item_id = ?", (item_id,)).fetchone()
    assert decision["decision"] == "approved"
    assert decision["status_before"] == "pending"
    assert decision["decided_by"] == "Jon"
    assert decision["note"] == "confirmed by hand"


def test_reverting_to_pending_clears_resolved_at_and_is_itself_recorded(seeded):
    item_id = ids_for(seeded, "Ambridge BC")
    review.decide(seeded, [item_id], "rejected", decided_by="Jon")
    review.decide(seeded, [item_id], "pending", decided_by="Jon", note="rejected in error")

    row = seeded.execute("SELECT * FROM review_queue WHERE id = ?", (item_id,)).fetchone()
    assert row["status"] == "pending"
    assert row["resolved_at"] is None

    history = seeded.execute(
        "SELECT decision, status_before FROM review_decisions "
        "WHERE review_item_id = ? ORDER BY id", (item_id,)).fetchall()
    assert [(r["decision"], r["status_before"]) for r in history] == [
        ("rejected", "pending"), ("pending", "rejected")]


def test_repeating_a_decision_writes_no_second_audit_row(seeded):
    """A double-click is not a second judgement."""
    item_id = ids_for(seeded, "Ambridge BC")
    review.decide(seeded, [item_id], "approved", decided_by="Jon")
    result = review.decide(seeded, [item_id], "approved", decided_by="Jon")

    assert result["updated"] == []
    assert result["unchanged"] == [item_id]
    assert seeded.execute(
        "SELECT COUNT(*) FROM review_decisions WHERE review_item_id = ?",
        (item_id,)).fetchone()[0] == 1


def test_repeating_a_decision_with_a_note_does_record_it(seeded):
    item_id = ids_for(seeded, "Ambridge BC")
    review.decide(seeded, [item_id], "approved", decided_by="Jon")
    review.decide(seeded, [item_id], "approved", decided_by="Sam", note="checked again")

    assert seeded.execute(
        "SELECT COUNT(*) FROM review_decisions WHERE review_item_id = ?",
        (item_id,)).fetchone()[0] == 2


def test_bulk_decision_reports_missing_ids_rather_than_failing(seeded):
    item_id = ids_for(seeded, "Ambridge BC")
    result = review.decide(seeded, [item_id, 9999], "rejected", decided_by="Jon")
    assert result["updated"] == [item_id]
    assert result["missing"] == [9999]


def test_a_decision_needs_a_reviewer_and_a_known_decision(seeded):
    item_id = ids_for(seeded, "Ambridge BC")
    with pytest.raises(review.DecisionError, match="reviewer name"):
        review.decide(seeded, [item_id], "approved", decided_by="  ")
    with pytest.raises(review.DecisionError, match="Unknown decision"):
        review.decide(seeded, [item_id], "deleted", decided_by="Jon")
    with pytest.raises(review.DecisionError, match="No items selected"):
        review.decide(seeded, [], "approved", decided_by="Jon")
    with pytest.raises(review.DecisionError, match="more than"):
        review.decide(seeded, list(range(review.MAX_BATCH + 1)), "approved", decided_by="Jon")


def test_deciding_a_filtered_set_needs_the_count_the_page_was_showing(seeded):
    """The guard that replaces the batch cap.

    If the set moved under the reviewer — someone else decided some, or a
    module added more — the count no longer matches and nothing happens.
    """
    with pytest.raises(review.DecisionError, match="not the 5"):
        review.decide_matching(seeded, decision="approved", decided_by="Jon",
                                confirm_count=5, module="m01_procurement")

    assert seeded.execute(
        "SELECT COUNT(*) FROM review_queue WHERE status = 'pending'").fetchone()[0] == 3

    result = review.decide_matching(seeded, decision="approved", decided_by="Jon",
                                     confirm_count=2, module="m01_procurement")
    assert result["matched"] == 2
    assert len(result["updated"]) == 2
    # Only the filtered module moved.
    assert seeded.execute(
        "SELECT COUNT(*) FROM review_queue WHERE status = 'pending'").fetchone()[0] == 1


def test_deciding_a_filtered_set_writes_the_same_audit_trail(seeded):
    review.decide_matching(seeded, decision="rejected", decided_by="Sam",
                            confirm_count=2, module="m01_procurement",
                            note="not English authorities")
    rows = seeded.execute(
        "SELECT decision, decided_by, note, status_before FROM review_decisions").fetchall()
    assert len(rows) == 2
    assert {r["decision"] for r in rows} == {"rejected"}
    assert {r["decided_by"] for r in rows} == {"Sam"}
    assert {r["status_before"] for r in rows} == {"pending"}


def test_an_unfiltered_bulk_decision_is_refused(seeded):
    """"Everything, unfiltered" is never a deliberate click, and it is the one
    mistake with no way back short of reading the audit trail."""
    with pytest.raises(review.DecisionError, match="entire queue"):
        review.decide_matching(seeded, decision="approved", decided_by="Jon",
                                confirm_count=3, status="all")


def test_the_bulk_filter_matches_exactly_what_the_list_shows(seeded, settings):
    """The set decided and the set displayed come from one predicate.

    Two copies of this filter that drift apart is a bulk action deciding items
    the reviewer was never shown, so it is pinned rather than assumed.
    """
    ro = queries.readonly_connection(settings)
    for filters in [
        {"module": "m01_procurement"},
        {"item_type": "unmatched_buyer_name"},
        {"search": "Barsetshire"},
        {"status": "pending", "module": "m04_companies"},
    ]:
        shown = queries.review_items(ro, limit=queries.MAX_PAGE_SIZE, **filters)
        clause, params = queries.review_filter_sql(
            filters.get("status", "pending"), filters.get("module"),
            filters.get("item_type"), filters.get("search"))
        matched = ro.execute(
            f"SELECT q.id FROM review_queue q{clause}", params).fetchall()
        assert {row["id"] for row in shown["items"]} == {r["id"] for r in matched}
    ro.close()


def test_bulk_decide_over_http(client, seeded):
    response = client.post("/api/review/decide-matching", json={
        "decision": "approved", "decided_by": "Jon",
        "confirm_count": 2, "module": "m01_procurement"})
    assert response.status_code == 200
    assert response.json()["matched"] == 2

    stale = client.post("/api/review/decide-matching", json={
        "decision": "approved", "decided_by": "Jon",
        "confirm_count": 99, "module": "m04_companies"})
    assert stale.status_code == 400
    assert "not the 99" in stale.json()["error"]


def test_a_decided_item_is_not_reopened_by_a_later_run(seeded):
    """The guarantee that makes deciding worth doing at all.

    record_review_item() upserts on (module, item_type, raw_value) and every
    module calls it on every run. If a re-run reset a decided item to pending,
    or overwrote the context under a decision already taken, the queue could
    never be cleared — which is why that upsert is conditional on the row
    still being pending, and why this test guards it from here.
    """
    item_id = ids_for(seeded, "Ambridge BC")
    review.decide(seeded, [item_id], "rejected", decided_by="Jon", note="not a provider")

    db.record_review_item(seeded, "m01_procurement", "unmatched_buyer_name", "Ambridge BC",
                           json.dumps({"contracts": 99}))

    row = seeded.execute("SELECT * FROM review_queue WHERE id = ?", (item_id,)).fetchone()
    assert row["status"] == "rejected"
    assert row["context_json"] is None


def test_decisions_travel_with_the_items_they_belong_to(seeded, settings):
    item_id = ids_for(seeded, "Ambridge BC")
    review.decide(seeded, [item_id], "approved", decided_by="Jon", note="verified")

    ro = queries.readonly_connection(settings)
    listed = queries.review_items(ro, status="approved")
    assert listed["total"] == 1
    assert listed["items"][0]["last_decided_by"] == "Jon"
    assert listed["items"][0]["last_note"] == "verified"

    full = queries.review_item(ro, item_id)
    assert len(full["decisions"]) == 1

    facets = queries.review_facets(ro)
    # 'answered' is counted alongside the three a person can set, even at zero.
    # It is a status items really hold — the pipeline closing a question it has
    # since answered — and leaving it out of the totals would drop those items
    # out of the overview without saying so.
    assert facets["statuses"] == {"pending": 2, "approved": 1, "rejected": 0,
                                   "answered": 0}
    ro.close()


def test_review_items_filter_by_module_type_and_text(seeded, settings):
    ro = queries.readonly_connection(settings)
    assert queries.review_items(ro, module="m04_companies")["total"] == 1
    assert queries.review_items(ro, item_type="unmatched_buyer_name")["total"] == 2
    assert queries.review_items(ro, search="Barsetshire")["total"] == 1
    # Context is searched as well as the raw value.
    assert queries.review_items(ro, search="Example Care")["total"] == 1
    assert queries.review_items(ro, status="all")["total"] == 3
    with pytest.raises(queries.QueryError):
        queries.review_items(ro, status="banished")
    ro.close()


# --- the HTTP layer -----------------------------------------------------------


@pytest.fixture
def client(seeded, settings):
    """A live server on an ephemeral port, and a client pointed at it."""
    server = build_server(settings, host="127.0.0.1", port=0)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    base = f"http://127.0.0.1:{server.server_address[1]}"
    try:
        with httpx.Client(base_url=base, timeout=10.0) as http:
            http.base = base
            yield http
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


def test_a_wildcard_bind_reports_addresses_other_machines_can_use():
    """"Listening on 0.0.0.0" is true and useless from another device."""
    urls = reachable_urls("0.0.0.0", 1801)
    assert urls[0] == "http://127.0.0.1:1801"
    assert urls == [f"http://{a}:1801" for a in ["127.0.0.1", *local_addresses()]]
    # A specific bind is reported as itself, not expanded.
    assert reachable_urls("127.0.0.1", 1801) == ["http://127.0.0.1:1801"]
    assert reachable_urls("10.2.0.90", 8080) == ["http://10.2.0.90:8080"]


def test_local_addresses_excludes_the_unreachable_ones():
    """Windows keeps a 169.254 link-local address on every idle adapter —
    Bluetooth, unused Ethernet, spare VPN interfaces. None is reachable, and
    printing them as ways in would send someone chasing a dead address."""
    for address in local_addresses():
        assert not address.startswith("127.")
        assert not address.startswith("169.254.")


def test_binding_a_wildcard_serves_requests(seeded, settings):
    """The LAN case, exercised over a real socket rather than assumed."""
    server = build_server(settings, host="0.0.0.0", port=0)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        port = server.server_address[1]
        with httpx.Client(timeout=10.0) as http:
            assert http.get(f"http://127.0.0.1:{port}/api/overview").status_code == 200
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


def test_a_write_from_a_non_loopback_origin_is_allowed_when_it_matches_the_host(client, seeded):
    """The CSRF guard compares Origin against the Host actually used, so
    reaching the UI on a LAN address works — the check is same-origin, not
    same-as-localhost. Getting this wrong would make every decision fail with
    a 403 for everyone except the machine running the server.
    """
    item_id = ids_for(seeded, "Ambridge BC")
    host = str(client.base_url.netloc, "utf-8") if isinstance(
        client.base_url.netloc, bytes) else str(client.base_url.netloc)
    response = client.post(
        "/api/review/decide",
        json={"ids": [item_id], "decision": "approved", "decided_by": "Jon"},
        headers={"Origin": f"http://{host}"},
    )
    assert response.status_code == 200


def test_serves_the_operator_page_and_its_assets(client):
    """The operator UI moved from / to /admin when the public portal took the
    root. Nothing else about it changed."""
    page = client.get("/admin/")
    assert page.status_code == 200
    assert "text/html" in page.headers["content-type"]
    assert client.get("/admin").status_code == 200
    assert client.get("/admin/app.js").status_code == 200
    assert client.get("/admin/styles.css").status_code == 200


def test_the_root_serves_the_public_portal_not_the_operator_ui(client):
    """Two front ends, one server. The root must not be the review queue —
    that is the whole reason the operator UI moved."""
    root = client.get("/").text
    admin = client.get("/admin/").text
    assert root != admin
    assert "SectorTrace" in root
    # The operator UI's own furniture must not appear on the public page.
    assert "review-list" not in root
    assert 'href="/admin"' in root or "/admin" in root


def test_vendored_libraries_are_served_and_cacheable(client):
    """They are the only static files big enough for a cache header to matter,
    and the only ones that change by someone replacing a file rather than by a
    module running."""
    response = client.get("/vendor/echarts.min.js")
    assert response.status_code == 200
    assert "max-age" in response.headers["cache-control"]
    assert "private" in response.headers["cache-control"]

    # Warehouse-backed responses must stay uncacheable.
    assert client.get("/api/overview").headers["cache-control"] == "no-store"


def test_unknown_paths_and_traversal_are_refused(client):
    assert client.get("/../../.env").status_code == 404
    assert client.get("/secrets/key.pem").status_code == 404
    assert client.get("/api/nonsense").status_code == 404


def test_overview_and_review_endpoints(client):
    overview = client.get("/api/overview").json()
    assert overview["review"]["statuses"]["pending"] == 3
    assert overview["parse_failures"]["total"] == 1
    assert overview["database"]["tables"] > 0

    listed = client.get("/api/review", params={"status": "pending", "limit": 2}).json()
    assert listed["total"] == 3
    assert len(listed["items"]) == 2

    assert client.get("/api/schema").json()["objects"]
    assert client.get("/api/review/999999").status_code == 404


def test_restricted_tables_need_a_second_ask(client):
    blocked = client.get("/api/table/restricted_people")
    assert blocked.status_code == 403
    assert "personal data" in blocked.json()["error"]

    revealed = client.get("/api/table/restricted_people", params={"reveal": "1"})
    assert revealed.status_code == 200
    assert revealed.json()["restricted"] is True

    # An ordinary table is never gated.
    assert client.get("/api/table/review_queue").status_code == 200


def test_deciding_over_http(client, seeded):
    item_id = ids_for(seeded, "Ambridge BC")
    response = client.post("/api/review/decide", json={
        "ids": [item_id], "decision": "approved", "decided_by": "Jon", "note": "ok"})
    assert response.status_code == 200
    assert response.json()["updated"] == [item_id]

    assert seeded.execute(
        "SELECT status FROM review_queue WHERE id = ?", (item_id,)).fetchone()[0] == "approved"


def test_a_bad_decision_is_a_400_with_a_readable_message(client, seeded):
    item_id = ids_for(seeded, "Ambridge BC")
    response = client.post("/api/review/decide", json={
        "ids": [item_id], "decision": "approved", "decided_by": ""})
    assert response.status_code == 400
    assert "reviewer name" in response.json()["error"]


def test_writes_require_a_json_content_type(client, seeded):
    """The CSRF guard. A form POST from another site cannot set this header,
    and a fetch that does triggers a preflight the browser will not pass."""
    item_id = ids_for(seeded, "Ambridge BC")
    response = client.post(
        "/api/review/decide",
        content=json.dumps({"ids": [item_id], "decision": "approved", "decided_by": "Jon"}),
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    assert response.status_code == 415
    assert seeded.execute(
        "SELECT status FROM review_queue WHERE id = ?", (item_id,)).fetchone()[0] == "pending"


def test_writes_from_another_origin_are_refused(client, seeded):
    item_id = ids_for(seeded, "Ambridge BC")
    response = client.post(
        "/api/review/decide",
        json={"ids": [item_id], "decision": "approved", "decided_by": "Jon"},
        headers={"Origin": "https://evil.example"},
    )
    assert response.status_code == 403
    assert seeded.execute(
        "SELECT status FROM review_queue WHERE id = ?", (item_id,)).fetchone()[0] == "pending"


def test_a_refused_write_leaves_the_connection_usable(client, seeded):
    """A refusal must consume the body it refused.

    httpx keeps the connection alive between these two calls. If the rejected
    POST's body were left sitting in the socket, this GET would be parsed out
    of those leftover bytes rather than read from the wire — the failure mode
    is a UI that breaks some actions *after* the one that went wrong.
    """
    item_id = ids_for(seeded, "Ambridge BC")
    refused = client.post(
        "/api/review/decide",
        content=json.dumps({"ids": [item_id], "decision": "approved", "decided_by": "Jon"}),
        headers={"Content-Type": "text/plain"},
    )
    assert refused.status_code == 415

    following = client.get("/api/review", params={"status": "pending"})
    assert following.status_code == 200
    assert following.json()["total"] == 3


def test_the_sql_endpoint_reads_but_cannot_write(client, seeded):
    ok = client.post("/api/query", json={"sql": "SELECT COUNT(*) AS n FROM review_queue"})
    assert ok.status_code == 200
    assert ok.json()["rows"] == [[3]]

    refused = client.post("/api/query", json={"sql": "DROP TABLE review_queue"})
    assert refused.status_code == 400
    assert seeded.execute(
        "SELECT COUNT(*) FROM pg_tables WHERE schemaname = current_schema() "
        "AND tablename = 'review_queue'").fetchone()[0] == 1
