"""Machine-owned documentation blocks (BETA-067).

Some facts in `docs/` are only a projection of an in-code registry — which
modules exist, what each collects, under what licence — and a prose copy of
them drifts. The committee-system capability line did: `docs/SOURCES.md`
listed CMIS and Democracy as sources next to a sentence saying only ModernGov
is searched.

This module renders those facts from the registries into delimited blocks.
`pipeline docs-check` fails (non-zero, with a diff) when a block is stale;
`pipeline docs-sync` rewrites them. Only the text *between* a block's markers
is ever touched — the narrative around it is hand-owned and left alone.

The registries read here:
  * `pipeline/web/datasets.py::DATASETS` — one row per collecting `mNN_`
    module (title, publisher, evidence layer, geography, cadence, tables),
    itself bound to the module registry by `tests/test_web_catalogue.py`.
  * `pipeline/licences.py` — each module's licence.
"""
from __future__ import annotations

import difflib
from collections.abc import Callable
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

_BEGIN = "<!-- BEGIN GENERATED: {name} -->"
_END = "<!-- END GENERATED: {name} -->"
_WARNING = (
    "<!-- Generated by `pipeline docs-sync` from pipeline/docs_matrix.py. "
    "Do not edit between the markers; run `pipeline docs-check` in CI. -->")


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|")


def source_capability_matrix() -> str:
    """One row per collecting module: its source, evidence layer, cadence,
    the public tables it writes and its licence. Every column is read from a
    registry, so a new module, a renamed table or a changed licence shows up
    the next time `docs-check` runs."""
    from pipeline import licences
    from pipeline.web import datasets

    rows = [
        "| Module | Source | Evidence layer | Cadence | Public tables | Licence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for dataset in sorted(datasets.DATASETS, key=lambda d: d.module):
        licence = licences.for_module(dataset.module)
        licence_name = licence.name if licence else "— (no licence recorded)"
        layer = datasets.EVIDENCE_LAYERS.get(
            dataset.evidence_layer, dataset.evidence_layer)
        tables = ", ".join(f"`{t}`" for t in dataset.public_tables) or "—"
        rows.append(
            f"| `{dataset.module}` | {_md_escape(dataset.publisher)} "
            f"| {_md_escape(layer)} | {_md_escape(dataset.cadence)} "
            f"| {tables} | {_md_escape(licence_name)} |")
    return "\n".join(rows)


# name -> (path relative to the repo root, renderer). The renderer returns the
# block body without the markers or the warning line.
GENERATED_BLOCKS: dict[str, tuple[Path, Callable[[], str]]] = {
    "source-capability-matrix": (
        REPO_ROOT / "docs" / "SOURCES.md", source_capability_matrix),
}


def _locate(text: str, name: str) -> tuple[int, int]:
    """The character span *between* a block's begin and end markers, newline
    boundaries included. Raises if the markers are missing or reversed."""
    begin = _BEGIN.format(name=name)
    end = _END.format(name=name)
    start = text.find(begin)
    stop = text.find(end)
    if start == -1 or stop == -1:
        raise KeyError(
            f"docs block {name!r}: markers {begin!r} / {end!r} not both present")
    if stop < start:
        raise ValueError(f"docs block {name!r}: end marker precedes begin marker")
    inner_start = text.index("\n", start) + 1
    return inner_start, stop


def _expected_body(name: str) -> str:
    renderer = GENERATED_BLOCKS[name][1]
    return f"{_WARNING}\n\n{renderer()}\n\n"


def render(name: str) -> str:
    """The full block for `name`, markers included — for a first insertion."""
    return (f"{_BEGIN.format(name=name)}\n{_expected_body(name)}"
            f"{_END.format(name=name)}\n")


def check(names: list[str] | None = None) -> list[dict]:
    """Every stale block, with a unified diff. Empty list means in sync.

    Read-only. A block whose file or markers are missing is reported as an
    error rather than silently skipped.
    """
    stale: list[dict] = []
    for name in names or list(GENERATED_BLOCKS):
        path, _ = GENERATED_BLOCKS[name]
        try:
            text = path.read_text(encoding="utf-8")
            lo, hi = _locate(text, name)
        except (OSError, KeyError, ValueError) as error:
            stale.append({"name": name, "path": str(path), "error": str(error)})
            continue
        current = text[lo:hi]
        expected = _expected_body(name)
        if current != expected:
            diff = "".join(difflib.unified_diff(
                current.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=f"{path.name}:{name} (committed)",
                tofile=f"{path.name}:{name} (generated)"))
            stale.append({"name": name, "path": str(path), "diff": diff})
    return stale


def sync(names: list[str] | None = None) -> list[str]:
    """Rewrite each stale block in place. Returns the names that changed."""
    changed: list[str] = []
    for name in names or list(GENERATED_BLOCKS):
        path, _ = GENERATED_BLOCKS[name]
        text = path.read_text(encoding="utf-8")
        lo, hi = _locate(text, name)
        expected = _expected_body(name)
        if text[lo:hi] == expected:
            continue
        path.write_text(text[:lo] + expected + text[hi:], encoding="utf-8")
        changed.append(name)
    return changed
