"""PostgreSQL schema helpers shared by the backup/restore path.

These moved out of `pgload.py` when the SQLite-to-PostgreSQL loader was removed
with the SQLite backend (performance.md Phase 1). They were never
SQLite-specific: each operates on a PostgreSQL connection — ordering the tables
a bulk load or a restore must write parents-first, pointing identity sequences
past ids that were copied verbatim, and emptying the data tables while keeping
the migration ledger. `pgbackup.py` is their caller now.
"""
from __future__ import annotations

from pipeline import catalog

# Tables a load/restore never writes as data: the migration ledger records what
# schema a database is and is applied, not copied.
SOURCE_ONLY_TABLES = frozenset({"schema_migrations"})

# Load-order edges the foreign-key graph does not carry but the settled-decision-4
# triggers require: a child whose promotion/verification trigger reads a parent
# table must be written after it. Kept explicit — and pinned by a test — so a
# trigger that needed an edge is never mistaken for one nobody accounted for.
TRIGGER_EDGES: dict[str, tuple[str, ...]] = {
    "cdp_documents": ("evidence_promotions",),
    "committee_papers": ("evidence_promotions",),
    "foi_requests": ("evidence_promotions",),
    "workforce_census_metrics": ("census_verifications",),
    "claims": ("claim_verifications",),
    # Migration 0049's `ai_promotion_requires_provenance` guards
    # evidence_promotions itself, but only against the row's own columns
    # (NEW.actor_id, NEW.model_id, ...) — it names no other table, so there is
    # no load-order dependency to add. Listed with an empty tuple anyway,
    # because the test below pins every trigger to an edge and a trigger that
    # needed nothing would otherwise look identical to one nobody had
    # accounted for yet.
    "evidence_promotions": (),
}


class LoadError(RuntimeError):
    """A load/restore that would produce a warehouse nobody should trust."""


def load_order(conn) -> list[str]:
    """Every table a load has to write, parents before children.

    Ties are broken by name so that two runs produce the same order and the
    state file from one is readable by the other. A cycle is raised on rather
    than resolved: this schema has none, and inventing an order for one would
    be choosing which foreign key to violate.
    """
    tables = [t for t in catalog.table_names(conn) if t not in SOURCE_ONLY_TABLES]
    known = set(tables)

    parents: dict[str, set[str]] = {t: set() for t in tables}
    for child, parent in catalog.foreign_keys(conn):
        if child in known and parent in known:
            parents[child].add(parent)
    for child, required in TRIGGER_EDGES.items():
        if child in known:
            parents[child].update(p for p in required if p in known)

    ordered: list[str] = []
    placed: set[str] = set()
    remaining = sorted(tables)
    while remaining:
        ready = [t for t in remaining if parents[t] <= placed]
        if not ready:
            raise LoadError(
                "the tables cannot be ordered for loading — these depend on "
                f"each other in a cycle: {', '.join(sorted(remaining))}")
        for table in ready:
            ordered.append(table)
            placed.add(table)
        remaining = [t for t in remaining if t not in placed]
    return ordered


def reset_sequences(target) -> list[dict]:
    """Point every identity sequence past the ids that were just loaded.

    The ids are copied verbatim so that every foreign key and every recorded
    `evidence_promotions.id` still points where it did — see the note in
    `pipeline/migrations/postgres/README.md` on why the columns are
    `GENERATED BY DEFAULT`. A sequence left at 1 afterwards would hand the
    next insert an id that is already taken, and the failure would arrive as a
    unique-violation on the first review decision somebody made.
    """
    rows = target.execute(
        "SELECT table_name AS tbl, column_name AS col "
        "FROM information_schema.columns "
        "WHERE table_schema = current_schema() AND is_identity = 'YES' "
        "ORDER BY table_name, column_name").fetchall()

    out = []
    for row in rows:
        table, column = row["tbl"], row["col"]
        # `+ 1, false` rather than `max, true`: an empty table has no maximum,
        # and `setval(seq, 0)` is below the sequence's minimum value and
        # raises. This spelling gives "the next value is max + 1" in both
        # cases.
        nxt = target.execute(
            f"SELECT setval(pg_get_serial_sequence(%s, %s), "
            f"COALESCE(MAX({catalog.quote(column)}), 0) + 1, false) "
            f"AS next_value FROM {catalog.quote(table)}", (table, column)).fetchone()["next_value"]
        out.append({"table": table, "column": column, "next_value": int(nxt)})
    return out


def truncate_all(target, tables: list[str]) -> None:
    """Empty the target's data tables, keeping its migration ledger.

    One statement listing every table, so the foreign keys between them are
    satisfied at the end of it without `CASCADE` — which would reach tables
    not on the list, and the one table not on the list is the ledger that
    records what schema this database is.
    """
    if not tables:
        return
    listed = ", ".join(catalog.quote(t) for t in tables)
    target.execute(f"TRUNCATE {listed} RESTART IDENTITY")
    target.commit()
