import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
const document = { record_type: 'document', record_id: 'doc-1', element_id: 'element-1', title: 'Original <script>text</script>', source_system: 'committee_papers', text: 'A source excerpt with an em dash — and semicolon; retained exactly.', link: 'javascript:alert(1)' }
const report = { record_type: 'coroner_report', record_id: 'pfd-1', title: 'Synthetic report', date: '2024-01-02', matched: { a: 'Organisation A', b: 'named_in' }, link: '#/pfd' }
const payload = { entities: [{ key: 'a', name: 'Organisation A', variant_count: 1 }, { key: 'b', name: 'Organisation B', variant_count: 1 }, { key: 'c', name: 'Organisation C', variant_count: 0 }], results: [document, report], note: 'Every row is one record that names all the selected entities.', caveat: 'Synthetic source caveat.', record_types: ['document', 'coroner_report'], counts: { by_record_type: { document: 1, coroner_report: 1 } } }
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://localhost:4173') throw new Error(`Unexpected external request: ${url.origin}`)
    if (url.pathname === '/api/v1/providers') return route.fulfill({ json: { providers: [{ provider_key: 'a', canonical_name: 'Organisation A' }, { provider_key: 'b', canonical_name: 'Organisation B' }] } })
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/map/')) return route.fulfill({ status: 503, json: { error: 'No fixture' } })
    return route.continue()
  })
})
test('co-mentions retains actual matches, missing provenance and exact document identities', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  const requests: URL[] = []
  await page.route('**/api/v1/cooccurrence?*', route => { requests.push(new URL(route.request().url())); return route.fulfill({ json: payload }) })
  await page.goto('/#/cooccurrence?key=a&key=b&key=c&year_from=2025')
  const navigation = page.getByRole('navigation', { name: 'Main sections', exact: true }).getByRole('link', { name: 'Connections', exact: true })
  await expect(navigation).toHaveCSS('border-left-color', 'rgb(52, 209, 191)')
  const records = page.getByRole('list', { name: 'Returned co-mention records' })
  await expect(records).toContainText(document.text)
  await expect(records).toContainText('named_in')
  expect(requests[0]!.searchParams.getAll('key')).toEqual(['a', 'b', 'c'])
  expect(requests[0]!.searchParams.has('year_from')).toBe(false)
  await expect(page.getByText('Structured records can match two or more selected keys.', { exact: false })).toBeVisible()
  await expect(page.getByText('No confirmed document-search variants are held for this key.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Inspect record 1', exact: true }).click()
  const inspector = page.getByRole('complementary', { name: 'Co-mention record', exact: true })
  await expect(inspector.getByRole('link', { name: 'Open document element' })).toHaveAttribute('href', '#/documents?doc=doc-1&el=element-1')
  await expect(inspector).toContainText('does not provide the record’s source URL')
  await expect(page.locator('a[href^="javascript:"]')).toHaveCount(0)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download returned reference JSON' }).click()
  expect(JSON.parse(readFileSync((await (await download).path())!, 'utf8')).rows).toEqual([payload])
  await page.getByRole('combobox', { name: 'Record type', exact: true }).selectOption('coroner_report')
  await expect(records).not.toContainText(document.text)
  await expect(inspector).toContainText(document.text)
  expect(requests).toHaveLength(1)
  await page.reload()
  await expect(inspector).toContainText(document.text)
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('combobox', { name: 'Colour theme' }).selectOption('light')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: info.outputPath('co-mentions-light.png'), fullPage: true, animations: 'disabled' })
})
test('co-mention key submission, local pages and duplicate record selection remain bounded', async ({ page }) => {
  let requests = 0
  const results = Array.from({ length: 26 }, (_, index) => ({ ...document, element_id: `el-${index}` }))
  await page.route('**/api/v1/cooccurrence?*', route => { requests++; return route.fulfill({ json: { ...payload, results } }) })
  await page.goto('/#/cooccurrence?key=a&key=a')
  await expect(page.getByText('Choose distinct keys.', { exact: false })).toBeVisible()
  expect(requests).toBe(0)
  await page.getByRole('textbox', { name: 'Organisation key 2', exact: true }).fill('b')
  expect(requests).toBe(0)
  await page.getByRole('button', { name: 'Find records', exact: true }).click()
  await expect(page.getByRole('list', { name: 'Returned co-mention records' }).getByRole('button')).toHaveCount(25)
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await page.getByRole('button', { name: 'Inspect record 26', exact: true }).click()
  expect(requests).toBe(1)
  const inspector = page.getByRole('complementary', { name: 'Co-mention record', exact: true })
  await expect(inspector).toContainText('el-25')
  await page.route('**/api/v1/cooccurrence?*', route => route.fulfill({ json: { ...payload, results: [results[25], results[25]] } }))
  await page.reload()
  await expect(inspector.getByText('The saved selection is missing, ambiguous or changed.', { exact: false })).toBeVisible()
})
test('mobile co-mentions retries unavailable data and distinguishes missing arrays', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/cooccurrence?key=a&key=b')
  await expect(page.getByRole('heading', { name: 'Evidence is unavailable' })).toBeVisible()
  await page.route('**/api/v1/cooccurrence?*', route => route.fulfill({ json: payload }))
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await page.getByRole('button', { name: 'Inspect record 2', exact: true }).click()
  const inspector = page.getByRole('dialog', { name: 'Co-mention record', exact: true })
  await expect(inspector.getByRole('link', { name: 'Open supporting evidence explorer' })).toHaveAttribute('href', '#/pfd')
  await page.screenshot({ path: info.outputPath('co-mentions-mobile.png'), animations: 'disabled' })
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await page.route('**/api/v1/cooccurrence?*', route => route.fulfill({ json: { ...payload, results: null } }))
  await page.reload()
  await expect(page.getByText('The result array was not supplied.', { exact: false })).toBeVisible()
})
