import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
const old = { id: 'same', label: 'Earlier view', href: '#/compare?provider_key=a&provider_key=b', at: 1 }
const imported = { ...old, label: 'Imported view' }
const file = (value: unknown) => ({ name: 'collection.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(value)) })
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://localhost:4173') throw new Error(`Unexpected external request: ${url.origin}`)
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/map/')) return route.fulfill({ status: 503, json: { error: 'No fixture' } })
    return route.continue()
  })
})
test('saved views import atomically, preserve collisions and round-trip repeated URL state', async ({ page }, info) => {
  await page.addInitScript(() => { if (!localStorage.getItem('st.saved')) localStorage.setItem('st.saved', JSON.stringify({ v: 1, data: [{ id: 'same', label: 'Earlier view', href: '#/compare?provider_key=a&provider_key=b', at: 1 }] })) })
  await page.goto('/#/saved')
  await page.getByLabel('Import collection JSON', { exact: true }).setInputFiles(file({ v: 1, data: [old, imported] }))
  await expect(page.getByRole('status')).toContainText('1 entry added. 1 exact duplicate skipped.')
  await expect(page.getByRole('link', { name: 'Earlier view', exact: true })).toHaveAttribute('href', old.href)
  await expect(page.getByRole('link', { name: 'Imported view', exact: true })).toBeVisible()
  await page.getByLabel('Import collection JSON', { exact: true }).setInputFiles(file({ v: 1, data: [{ ...old, href: 'javascript:alert(1)' }] }))
  await expect(page.getByText('No entries were imported.', { exact: false })).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export collection JSON' }).click()
  const exported = JSON.parse(readFileSync((await (await download).path())!, 'utf8'))
  expect(exported.entries).toHaveLength(2)
  expect(exported.entries[0]).toEqual(old)
  expect(exported.entries[1].id).not.toBe('same')
  expect(exported.entries[1].href).toBe(old.href)
  await page.getByRole('button', { name: 'Remove Imported view', exact: true }).click()
  await page.getByLabel('Import collection JSON', { exact: true }).setInputFiles(file(exported))
  await expect(page.getByRole('link', { name: 'Imported view', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('link', { name: 'Earlier view', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Imported view', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('saved-collections.png'), fullPage: true })
})
test('notebook import remains exportable when storage fails and preserves exact note text', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new Error('Fixture storage unavailable') } })
  await page.goto('/#/notebook')
  const entry = { id: 'note', title: 'Original reference', href: '/documents?element_id=missing', at: 1, note: 'My note\nQuoted text: <script>never execute</script> — exact; punctuation.' }
  await page.getByLabel('Import collection JSON', { exact: true }).setInputFiles(file({ format: 'sectortrace-collection', version: 1, kind: 'notebook', entries: [entry] }))
  await expect(page.getByRole('status')).toContainText('Browser storage is unavailable.')
  await expect(page.getByRole('link', { name: entry.title })).toHaveAttribute('href', '#/documents?element_id=missing')
  await expect(page.getByText(entry.note, { exact: true })).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export collection JSON' }).click()
  const exported = JSON.parse(readFileSync((await (await download).path())!, 'utf8'))
  expect(exported.entries).toEqual([entry])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Clear notebook', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('link', { name: entry.title })).toBeVisible()
})

test('personal notebook edits preserve source text, export separately and restore focus', async ({ page }, info) => {
  await page.goto('/#/notebook')
  const original = { id: 'edit-note', title: 'Published reference', href: '#/documents?element_id=old', at: 1, note: 'Original quoted text; punctuation — retained.' }
  await page.getByLabel('Import collection JSON', { exact: true }).setInputFiles(file({ v: 1, data: [original] }))
  const trigger = page.getByRole('button', { name: 'Edit personal note for Published reference', exact: true })
  await trigger.click()
  const input = page.getByRole('textbox', { name: 'Personal note', exact: true })
  await expect(input).toBeFocused()
  await input.fill('My separate interpretation.\nFollow up with the source.')
  await page.getByRole('button', { name: 'Save personal note', exact: true }).click()
  await expect(trigger).toBeFocused()
  await expect(page.getByText(original.note, { exact: true })).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export collection JSON' }).click()
  const exported = JSON.parse(readFileSync((await (await download).path())!, 'utf8'))
  expect(exported.entries).toEqual([{ ...original, annotation: 'My separate interpretation.\nFollow up with the source.' }])
  await page.reload()
  await page.setViewportSize({ width: 390, height: 844 })
  await trigger.click()
  await expect(input).toHaveValue(exported.entries[0].annotation)
  await page.screenshot({ path: info.outputPath('notebook-editor-mobile.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await input.fill('Draft that must not replace a removed entry')
  await page.getByRole('button', { name: 'Remove Published reference', exact: true }).click()
  await page.getByRole('button', { name: 'Save personal note', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('No entry was overwritten.')
  await expect(input).toHaveValue('Draft that must not replace a removed entry')
})
