import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
const indicator = { indicator_id: 1, indicator_name: 'Treatment observations', unit: 'People', definition: 'Synthetic population definition.', topic: 'numbers_in_treatment', substance: 'opiate', source_url: 'https://example.invalid/indicator', retrieved_at: '2026-08-01' }
const row = { indicator_id: 1, ons_code: 'E00000001', authority_name: 'Authority 1', time_period: '2024/25', time_period_sortable: 2024, value: 12, lower_ci_95: 10, upper_ci_95: 15, source_url: 'https://example.invalid/observation', retrieved_at: '2026-09-01' }
const treatment = { rows: [row, { ...row, indicator_id: 2, value: 900 }], indicators: [indicator, { ...indicator, indicator_id: 2, indicator_name: 'Other population', unit: 'Percent' }], england: [{ indicator_id: 1, time_period: '2024/25', value: 100 }], caveat: 'Synthetic treatment caveat.' }
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://localhost:4173') throw new Error(`Unexpected external request: ${url.origin}`)
    if (url.pathname === '/api/v1/providers') return route.fulfill({ json: { providers: [] } })
    if (url.pathname === '/api/v1/authorities') return route.fulfill({ json: { authorities: [{ ons_code: 'E00000001', name: 'Authority 1' }, { ons_code: 'E00000002', name: 'Authority 2' }] } })
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/map/')) return route.fulfill({ status: 503, json: { error: 'No fixture' } })
    return route.continue()
  })
})
test('treatment comparison selects one indicator, retains confidence bounds and separates England provenance', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  let requests = 0
  await page.route('**/api/v1/compare?*', route => { requests++; return route.fulfill({ json: { authorities: [], providers: [], series: { treatment } } }) })
  await page.goto('/#/compare?ons_code=E00000001&ons_code=E00000002&lens=treatment')
  await expect(page.getByText('Select one unambiguous returned indicator.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Download annotated chart PNG', exact: true })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Treatment indicator', exact: true }).selectOption('1')
  const chart = page.getByRole('region', { name: 'E00000001 Treatment observations chart', exact: true })
  await expect(chart.locator('svg')).toHaveCount(1)
  await expect(page.getByText('E00000002: no returned observations for this indicator.', { exact: false })).toBeVisible()
  const records = page.getByRole('region', { name: 'Treatment observations authority observations records', exact: true })
  await expect(records.getByRole('cell', { name: '900', exact: true })).toHaveCount(0)
  await page.screenshot({ path: info.outputPath('treatment-comparison-page.png'), fullPage: true })
  const png = page.waitForEvent('download')
  await chart.getByRole('button', { name: 'Download annotated chart PNG' }).click()
  await (await png).saveAs(info.outputPath('treatment-comparison.png'))
  await page.getByRole('button', { name: 'Inspect E00000001 observation 1', exact: true }).click()
  const inspector = page.getByRole('complementary', { name: 'Comparison record', exact: true })
  await expect(inspector).toContainText('lower ci 95')
  await expect(inspector).toContainText('https://example.invalid/observation')
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByText('England reference observations', { exact: true }).click()
  const england = page.getByRole('region', { name: 'England treatment reference records', exact: true })
  const download = page.waitForEvent('download')
  await england.getByRole('button', { name: 'Download source reference JSON', exact: true }).click()
  const exported = JSON.parse(readFileSync((await (await download).path())!, 'utf8'))
  expect(exported.rows).toEqual(treatment.england)
  expect(exported.rows[0].source_url).toBeUndefined()
  expect(requests).toBe(1)
  await page.getByRole('button', { name: 'Data', exact: true }).click()
  await expect(chart).toHaveCount(0)
  await expect(page).toHaveURL(/view=data/)
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Treatment indicator', exact: true })).toHaveValue('1')
  await expect(records.getByRole('cell', { name: '12', exact: true })).toBeVisible()
})
test('treatment comparison does not substitute duplicate indicator metadata or a missing unit', async ({ page }) => {
  await page.route('**/api/v1/compare?*', route => route.fulfill({ json: { authorities: [], providers: [], series: { treatment: { ...treatment, indicators: [indicator, { ...indicator, unit: 'Different unit' }] } } } }))
  await page.goto('/#/compare?ons_code=E00000001&lens=treatment&indicator=1')
  await expect(page.getByText('Select one unambiguous returned indicator.', { exact: false })).toBeVisible()
  await page.route('**/api/v1/compare?*', route => route.fulfill({ json: { authorities: [], providers: [], series: { treatment: { ...treatment, indicators: [{ ...indicator, unit: null }] } } } }))
  await page.reload()
  await expect(page.getByText('The indicator unit was not supplied.', { exact: false })).toBeVisible()
  await expect(page.getByRole('cell', { name: '12', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Download annotated chart PNG' })).toHaveCount(0)
})

test('mobile treatment comparison distinguishes an absent row array from an empty observation set', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.route('**/api/v1/compare?*', route => route.fulfill({ json: { authorities: [], providers: [], series: { treatment: { indicators: [indicator] } } } }))
  await page.goto('/#/compare?ons_code=E00000001&lens=treatment&indicator=1')
  await expect(page.getByText('The source did not supply a row array for this table.', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('E00000001: no observations were returned in this source.', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Download annotated chart PNG' })).toHaveCount(0)
  await page.route('**/api/v1/compare?*', route => route.fulfill({ json: { authorities: [], providers: [], series: { treatment } } }))
  await page.reload()
  await page.getByRole('button', { name: 'Inspect E00000001 observation 1', exact: true }).click()
  const inspector = page.getByRole('dialog', { name: 'Comparison record', exact: true })
  await expect(inspector).toBeVisible()
  await expect(inspector).toContainText('lower ci 95')
  await page.screenshot({ path: info.outputPath('treatment-comparison-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
