import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://localhost:4173') throw new Error(`Unexpected external request: ${url.origin}`)
    if (url.pathname === '/api/v1/providers') return route.fulfill({ json: { providers: [{ provider_key: 'p1', canonical_name: 'Provider 1' }, { provider_key: 'p2', canonical_name: 'Provider 2' }] } })
    if (url.pathname === '/api/v1/authorities') return route.fulfill({ json: { authorities: [] } })
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/map/')) return route.fulfill({ status: 503, json: { error: 'No fixture' } })
    return route.continue()
  })
})
test('comparison peer charts preserve source rows, bounds, inspection and annotated exports', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  let requests = 0
  const rows = Array.from({ length: 13 }, (_, index) => ({ provider_key: 'p1', financial_year_end: '2024-03-31', total_income: index === 1 ? null : index * 100, total_expenditure: index * 50, source_url: 'https://example.invalid/accounts', retrieved_at: '2026-09-01', payload_sha256: 'fixture-hash' }))
  await page.route('**/api/v1/compare?*', route => { requests++; return route.fulfill({ json: { providers: [], authorities: [], series: { charity: { rows, caveat: 'Synthetic charity caveat.' }, provider_contracts: { rows: [{ provider_key: 'p1', year: 2025, count: 2, value_gbp: 999999 }] } } } }) })
  await page.goto('/#/compare?provider_key=p1&provider_key=p2')
  const chart = page.getByRole('region', { name: 'Provider 1 Charity income and expenditure chart', exact: true })
  await expect(chart.locator('svg')).toHaveCount(1)
  await expect(chart.getByRole('button', { name: /^Inspect plotted record / })).toHaveCount(12)
  await expect(page.getByText('Provider 2: no source records in this chart group.', { exact: true })).toBeVisible()
  const svgDownload = page.waitForEvent('download')
  await chart.getByRole('button', { name: 'Download peer chart SVG' }).click()
  const svg = readFileSync((await (await svgDownload).path())!, 'utf8')
  const text = await page.evaluate(value => Array.from(new DOMParser().parseFromString(value, 'image/svg+xml').querySelectorAll('text')).map(node => node.textContent).join(''), svg)
  expect(text).toContain('fixture-hash')
  expect(text.replaceAll(/\s/g, '')).toContain('Syntheticcharitycaveat.')
  const pngDownload = page.waitForEvent('download')
  await chart.getByRole('button', { name: 'Download peer chart PNG' }).click()
  await (await pngDownload).saveAs(info.outputPath('comparison-peer-chart.png'))
  const record = chart.getByRole('button', { name: 'Inspect plotted record 1', exact: true })
  await record.focus()
  await record.press('Enter')
  await expect(record).toHaveAttribute('aria-pressed', 'true')
  const inspector = page.getByRole('complementary', { name: 'Comparison record', exact: true })
  await expect(inspector).toContainText('fixture-hash')
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Next chart group', exact: true }).click()
  await expect(chart.getByRole('button', { name: 'Inspect plotted record 13', exact: true })).toBeVisible()
  await expect(chart.getByRole('button', { name: /^Inspect plotted record / })).toHaveCount(1)
  await page.getByRole('button', { name: 'Data', exact: true }).click()
  await expect(chart).toHaveCount(0)
  expect(requests).toBe(1)
  await page.getByRole('combobox', { name: 'Evidence source', exact: true }).selectOption('provider_contracts')
  await page.getByRole('button', { name: 'Chart', exact: true }).click()
  await page.getByRole('button', { name: 'First chart group', exact: true }).click()
  const counts = page.getByRole('region', { name: 'Provider 1 Contract notice counts chart', exact: true })
  await expect(counts.locator('svg')).toHaveCount(1)
  await expect(counts.locator('svg')).not.toContainText('999999')
  await expect(counts.locator('svg text').filter({ hasText: /^0\.5$/ })).toHaveCount(0)
  expect(requests).toBe(1)
  await page.getByRole('combobox', { name: 'Colour theme' }).selectOption('light')
  await expect(counts.locator('svg text').first()).toHaveAttribute('fill', '#070707')
  await page.getByRole('heading', { level: 1 }).evaluate(element => (element as HTMLElement).focus({ preventScroll: true }))
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: info.outputPath('comparison-counts-light.png'), fullPage: true, animations: 'disabled' })
})
