import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
const provider = { provider_key: 'example-recovery', canonical_name: 'Example Recovery' }
const authority = { ons_code: 'E00000001', name: 'Example Authority' }
const graphProvider = { entity_id: 'graph-provider', entity_type: 'PROVIDER', canonical_name: provider.canonical_name }
const graphAuthority = { entity_id: 'graph-authority', entity_type: 'LOCAL_AUTHORITY', canonical_name: authority.name }
const edge = (id: string) => ({ relationship_id: id, subject_entity_id: graphAuthority.entity_id, object_entity_id: graphProvider.entity_id, valid_from: '2020-01-01', valid_to: null, confidence: 'HIGH', source_url: 'https://example.invalid/relationship-source', retrieved_at: '2026-09-01', source_system: 'find_a_tender' })
const detail = { relationship_id: 'edge-1', predicate: 'AWARDED_TO', authority: { entity_id: graphAuthority.entity_id, name: authority.name, ons_code: authority.ons_code }, provider: { entity_id: graphProvider.entity_id, name: provider.canonical_name, provider_key: provider.provider_key }, truncated: true, edge_count: 2, caveat: 'Synthetic history is bounded and describes a pair.', timeline: [{ relationship_id: 'edge-1', valid_from: '2020-01-01', valid_to: null, confidence: 'HIGH', source_url: 'https://example.invalid/relationship-source', retrieved_at: '2026-09-01', notice: { notice_id: 'notice-1', title: 'Notice <script>unsafe</script>', value_core: 0, currency: 'EUR', date_published: '2021-03-04', source_url: 'https://example.invalid/notice-source', retrieved_at: '2026-08-01', notice_web_url: 'https://example.invalid/constructed-notice' } }, { relationship_id: 'edge-2', valid_from: null, valid_to: null, source_url: 'https://example.invalid/second-edge', retrieved_at: null, notice: null }] }
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://localhost:4173') throw new Error(`Unexpected external request: ${url.origin}`)
    if (url.pathname === '/api/v1/providers') return route.fulfill({ json: { providers: [provider] } })
    if (url.pathname === '/api/v1/authorities') return route.fulfill({ json: { authorities: [authority] } })
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/map/')) return route.fulfill({ status: 503, json: { error: 'No fixture for this request' } })
    return route.continue()
  })
})

test('commissioning diagram preserves graph identities, dated edges, source scopes and annotated exports', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  const requests: URL[] = []
  let details = 0
  const edges = [...Array.from({ length: 13 }, (_, i) => edge(`edge-${i + 1}`)), { ...edge('edge-unknown'), subject_entity_id: 'unreturned-node' }]
  await page.route('**/api/v1/relationships?*', route => { requests.push(new URL(route.request().url())); return route.fulfill({ json: { center: graphProvider, neighbours: [graphAuthority], edges, caveat: 'Synthetic commissioning caveat.' } }) })
  await page.route('**/api/v1/relationships/edge-1', route => { details++; return route.fulfill({ json: detail }) })
  await page.goto('/#/relationships?provider_key=example-recovery&year_from=2025')
  const diagram = page.getByRole('region', { name: 'Commissioning relationship diagram', exact: true })
  await expect(diagram.getByRole('button', { name: /Inspect relationship edge-/ })).toHaveCount(12)
  expect(details).toBe(0)
  expect(Object.fromEntries(requests[0]!.searchParams)).toEqual({ provider_key: provider.provider_key })
  const svgDownload = page.waitForEvent('download')
  await diagram.getByRole('button', { name: 'Download annotated diagram SVG' }).click()
  const svg = readFileSync((await (await svgDownload).path())!, 'utf8')
  expect(svg).toContain('AWARDED_TO')
  const exportedText = await page.evaluate(value => Array.from(new DOMParser().parseFromString(value, 'image/svg+xml').querySelectorAll('text')).map(node => node.textContent).join(''), svg)
  expect(exportedText).toContain('https://example.invalid/relationship-source')
  expect(exportedText).toContain('Diagram numbers are display labels, not source identifiers.')
  expect(exportedText).toContain('Diagram edge 12, relationship edge-12')
  expect(exportedText.match(/URL https:\/\/example.invalid\/relationship-source/g)).toHaveLength(1)
  const pngDownload = page.waitForEvent('download')
  await diagram.getByRole('button', { name: 'Download annotated diagram PNG' }).click()
  await (await pngDownload).saveAs(info.outputPath('commissioning-annotated.png'))
  await diagram.getByRole('button', { name: 'Inspect graph entity Example Recovery', exact: true }).click()
  const node = page.getByRole('complementary', { name: 'Graph entity', exact: true })
  await expect(node).toContainText('graph-provider')
  await expect(node.getByRole('link')).toHaveCount(0)
  await node.getByRole('button', { name: 'Close', exact: true }).click()
  const actualEdge = diagram.getByRole('button', { name: 'Inspect relationship edge-1: Example Authority awarded to Example Recovery', exact: true })
  await actualEdge.focus()
  await actualEdge.press('Enter')
  await expect(actualEdge).toHaveAttribute('aria-pressed', 'true')
  await expect(actualEdge).toHaveAttribute('stroke-dasharray', '8 4')
  const inspector = page.getByRole('complementary', { name: 'Relationship edge-1', exact: true })
  await expect(inspector.getByRole('link', { name: 'Open provider profile', exact: true })).toHaveAttribute('href', '#/providers/example-recovery')
  await expect(inspector.getByRole('link', { name: 'Open authority profile', exact: true })).toHaveAttribute('href', '#/authorities/E00000001')
  await expect(inspector.getByText('2021-03-04', { exact: true })).toBeVisible()
  await expect(inspector.getByText('EUR', { exact: true })).toBeVisible()
  await expect(inspector.getByText('0', { exact: true })).toBeVisible()
  await expect(inspector.getByText('The notice is not available', { exact: false })).toBeVisible()
  await expect(inspector.getByText('The history was truncated', { exact: false })).toBeVisible()
  const historyDownload = page.waitForEvent('download')
  await inspector.getByRole('button', { name: 'Download returned pair history JSON' }).click()
  const history = JSON.parse(readFileSync((await (await historyDownload).path())!, 'utf8'))
  expect(history.rows).toEqual([detail])
  await page.getByRole('button', { name: 'Data', exact: true }).click()
  await expect(page).toHaveURL(/view=data/)
  expect(requests).toHaveLength(1)
  expect(details).toBe(1)
  await page.reload()
  await expect(inspector).toBeVisible()
  await expect(page.getByRole('button', { name: 'Data', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Diagram', exact: true }).click()
  await page.getByRole('button', { name: 'Next diagram group' }).click()
  await expect(diagram.getByRole('button', { name: /Inspect relationship edge-/ })).toHaveCount(1)
  await expect(page.getByRole('region', { name: 'Commissioning edge data', exact: true })).toContainText('edge-unknown')
  await page.getByRole('combobox', { name: 'Colour theme' }).selectOption('light')
  await expect(diagram.locator('svg > text').first()).toHaveAttribute('fill', '#070707')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: info.outputPath('commissioning-light.png'), fullPage: true, animations: 'disabled' })
})

test('commissioning centre and detail failures remain explicit without hiding edge data', async ({ page }, info) => {
  let requests = 0
  await page.setViewportSize({ width: 390, height: 844 })
  await page.route('**/api/v1/relationships?*', route => { requests++; return route.fulfill({ json: { center: graphProvider, neighbours: [graphAuthority], edges: [edge('edge-1')], caveat: null } }) })
  await page.goto('/#/relationships?provider_key=example-recovery&ons_code=E00000001')
  await expect(page.getByText('This view needs one centre.', { exact: false })).toBeVisible()
  expect(requests).toBe(0)
  await page.getByRole('button', { name: 'Clear centre' }).click()
  await expect(page.getByText('Choose an authority or provider to inspect', { exact: false })).toBeVisible()
  await page.getByRole('combobox', { name: 'Provider', exact: true }).selectOption(provider.provider_key)
  await expect(page.getByRole('button', { name: 'Data', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('svg[aria-label="Authorities awarded to providers"]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Inspect relationship edge-1, displayed row 1', exact: true }).click()
  const inspector = page.getByRole('dialog', { name: 'Relationship edge-1', exact: true })
  await expect(inspector.getByRole('heading', { name: 'Evidence is unavailable' })).toBeVisible()
  await page.route('**/api/v1/relationships/edge-1', route => route.fulfill({ json: detail }))
  await inspector.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(inspector.getByRole('link', { name: 'Open provider profile', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('commissioning-mobile-inspector.png'), animations: 'disabled' })
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Commissioning edge data', exact: true })).toContainText('edge-1')
  expect(requests).toBe(1)
})

test('commissioning does not choose duplicate nodes or duplicate saved relationships', async ({ page }) => {
  await page.route('**/api/v1/relationships?*', route => route.fulfill({ json: { center: graphProvider, neighbours: [graphAuthority, { ...graphAuthority, canonical_name: 'Conflicting authority name' }], edges: [edge('same'), edge('same')], caveat: null } }))
  await page.goto('/#/relationships?provider_key=example-recovery&relationship_id=same')
  await expect(page.getByText('The saved relationship identifier does not identify one edge', { exact: false })).toBeVisible()
  await page.goto('/#/relationships?provider_key=example-recovery&node=graph-authority')
  await expect(page.getByText('The graph identifier does not identify one returned node.', { exact: false })).toBeVisible()
  await expect(page.locator('svg path')).toHaveCount(0)
  await page.route('**/api/v1/relationships?*', route => route.fulfill({ json: { center: graphProvider, caveat: null } }))
  await page.reload()
  await expect(page.getByText('The relationship array was not supplied.', { exact: false })).toBeVisible()
})
