import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://localhost:4173') throw new Error(`Unexpected external request: ${url.origin}`)
    if (url.pathname === '/api/v1/providers') return route.fulfill({ json: { providers: [{ provider_key: 'p1', canonical_name: 'Provider 1' }] } })
    if (url.pathname === '/api/v1/authorities') return route.fulfill({ json: { authorities: [] } })
    if (url.pathname === '/api/v1/compare') return route.fulfill({ json: { series: { charity: { rows: [{ provider_key: 'p1', total_income: 12, financial_year_end: '2024-03-31' }] } } } })
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/map/')) return route.fulfill({ status: 503, json: { error: 'No fixture' } })
    return route.continue()
  })
})

test('inspector resizing preserves evidence width, local preference and keyboard access', async ({ page }, info) => {
  await page.goto('/#/compare?provider_key=p1&lens=charity&view=data')
  const trigger = page.getByRole('button', { name: 'Inspect record 1', exact: true })
  await trigger.click()
  const inspector = page.getByRole('complementary', { name: 'Comparison record', exact: true })
  const separator = page.getByRole('separator', { name: 'Resize Comparison record inspector' })
  await expect(inspector.getByRole('heading', { name: 'Comparison record', exact: true })).toBeFocused()
  await expect(separator).toHaveAttribute('aria-valuenow', '360')
  await separator.focus()
  await page.keyboard.press('ArrowLeft')
  await expect(separator).toHaveAttribute('aria-valuenow', '370')
  const box = (await separator.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + 30)
  await page.mouse.down()
  await page.mouse.move(box.x - 30 + box.width / 2, box.y + 30)
  await page.mouse.up()
  await expect(separator).toHaveAttribute('aria-valuenow', '400')
  await page.reload()
  await expect(separator).toHaveAttribute('aria-valuenow', '400')
  await separator.focus()
  await page.keyboard.press('End')
  await expect(separator).toHaveAttribute('aria-valuenow', '560')
  const sizes = await page.locator('.st-inspector-host').evaluate(host => ({ main: host.firstElementChild!.getBoundingClientRect().width, inspector: host.querySelector('aside')!.getBoundingClientRect().width }))
  expect(sizes.main).toBeGreaterThanOrEqual(480)
  expect(sizes.inspector).toBe(560)
  await inspector.getByRole('button', { name: 'Reset inspector width' }).click()
  await expect(separator).toHaveAttribute('aria-valuenow', '360')
  await inspector.getByRole('heading', { name: 'Comparison record', exact: true }).evaluate(node => (node as HTMLElement).focus({ preventScroll: true }))
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  await page.screenshot({ path: info.outputPath('resizable-inspector.png'), fullPage: true })
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await trigger.click()
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.setViewportSize({ width: 1200, height: 900 })
  await page.locator('.st-inspector-host').evaluate(host => { (host as HTMLElement).style.width = '800px' })
  await expect(page.getByRole('dialog', { name: 'Comparison record', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('inspector width remains usable when storage is blocked', async ({ page }) => {
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new Error('Storage blocked by fixture') } })
  await page.goto('/#/compare?provider_key=p1&lens=charity&view=data')
  await page.getByRole('button', { name: 'Inspect record 1', exact: true }).click()
  const separator = page.getByRole('separator', { name: 'Resize Comparison record inspector' })
  await separator.focus()
  await page.keyboard.press('Home')
  await expect(separator).toHaveAttribute('aria-valuenow', '320')
  await expect(page.getByText('This browser could not save the layout.', { exact: false })).toBeVisible()
})
