import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
const provider = { provider_key: 'example-recovery', canonical_name: 'Example Recovery' }
const event = (source: string, date: string | null, relationship: string, title: string) => ({ source, date, relationship, title, entity_type: 'provider', entity_key: provider.provider_key, entity_name: provider.canonical_name, source_url: `https://example.invalid/${source}`, detail: 'Synthetic source detail', result: null as string | null })
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://localhost:4173') throw new Error(`Unexpected external request: ${url.origin}`)
    if (url.pathname === '/api/v1/providers') return route.fulfill({ json: { providers: [provider] } })
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/map/')) return route.fulfill({ status: 503, json: { error: 'No fixture for this request' } })
    return route.continue()
  })
})

test('safety keeps source lanes, relationships, uncertain dates and reference scope distinct', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  const requests: URL[] = []
  const rows = [event('pfd', 'March 2026', 'named_in', 'Partial-date report'), event('pfd', null, 'named_in', 'Undated report'), event('pfd', '2025-12-31', 'addressed_to', 'Older report'), event('pfd', '12 March 2026', 'addressed_to', 'Newer report'), event('pfd', '12 March 2026', 'named_in', 'Newer report'), event('sar', null, 'named_in', 'SAR library item'), { ...event('hse', '2026-01-01', 'matched_to', 'HSE notice'), result: 'Withdrawn following appeal' }, event('tribunal', '2026-01-02', 'named_in', 'Tribunal case')]
  await page.route('**/api/v1/safety_legal*', route => { requests.push(new URL(route.request().url())); return route.fulfill({ json: { events: rows, truncated: true, caveats: { pfd: 'Synthetic report relationships are separate.' } } }) })
  await page.goto('/#/pfd?provider_key=example-recovery&ons_code=E00000001')
  await expect(page.getByRole('textbox', { name: 'First source year', exact: true })).toHaveCSS('border-top-style', 'solid')
  const pfd = page.getByRole('region', { name: 'Coroners’ reports', exact: true })
  await expect(pfd.getByRole('heading', { name: 'Dated entries, newest first' })).toBeVisible()
  const entries = pfd.getByRole('list', { name: 'Coroners’ reports chronology' }).getByRole('listitem')
  await expect(entries).toHaveCount(5)
  await expect(entries.nth(0)).toContainText('Newer report')
  await expect(entries.nth(1)).toContainText('Named in')
  await expect(entries.nth(2)).toContainText('Older report')
  await expect(entries.nth(3)).toContainText('Other published date text')
  await expect(entries.nth(4)).toContainText('Undated entries')
  await expect(page.getByText('The source response is truncated.', { exact: false })).toBeVisible()
  await expect(page.getByText('The retained authority selection does not filter this response.', { exact: false })).toBeVisible()
  expect(Object.fromEntries(requests[0]!.searchParams)).toEqual({ provider_key: provider.provider_key })
  await entries.nth(1).getByRole('button').click()
  const inspector = page.getByRole('complementary', { name: 'Newer report', exact: true })
  await expect(inspector).toBeVisible()
  await expect(inspector.getByText('Named in', { exact: true })).toBeVisible()
  await inspector.getByRole('button', { name: 'Save evidence reference', exact: true }).click()
  await expect(inspector.getByText('Evidence reference saved', { exact: false })).toBeVisible()
  const download = page.waitForEvent('download')
  await pfd.getByRole('button', { name: 'Download reference manifest', exact: true }).click()
  const manifest = JSON.parse(readFileSync((await (await download).path())!, 'utf8'))
  expect(manifest.rows).toHaveLength(5)
  expect(manifest.rows[0]).toMatchObject({ retrieved_at: null, payload_sha256: null, source_date: '12 March 2026' })
  expect(manifest.rows[1].relationship).toBe('named_in')
  expect(manifest._provenance.request_filters).toEqual({ provider_key: provider.provider_key })
  expect(manifest._provenance.source_array).toBe('events[source=pfd]')
  await pfd.getByRole('button', { name: 'Data', exact: true }).click()
  await expect(page).toHaveURL(/pfd-events_view=data/)
  expect(requests).toHaveLength(1)
  await page.reload()
  await expect(inspector).toBeVisible()
  await expect(pfd.getByRole('button', { name: 'Data', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByRole('region', { name: 'HSE enforcement notices', exact: true })).toContainText('Withdrawn following appeal')
  await expect(page.getByRole('region', { name: 'Safeguarding Adult Reviews', exact: true })).toContainText('Undated entries')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: info.outputPath('safety-source-lanes-dark.png'), fullPage: true, animations: 'disabled' })
})

test('safety collections remain unfiltered and retain SAR library years and PFD stubs', async ({ page }, info) => {
  const requests: URL[] = []
  let eventRequests = 0
  await page.route('**/api/v1/safety', route => { expect(new URL(route.request().url()).search).toBe(''); return route.fulfill({ json: { notices: [{ notice_number: 'N-1', provider_key: provider.provider_key, recipient_name: provider.canonical_name, issue_date: '2025-03-01', compliance_date: '2025-04-01', revised_compliance_date: '2025-05-01', result: 'Withdrawn following appeal', source_url: 'https://example.invalid/hse', retrieved_at: '2026-09-01' }], total: 1, by_type: [], by_provider: [], caveat: 'Synthetic register results remain attached to notices.' } }) })
  await page.route('**/api/v1/safety_legal*', route => { eventRequests++; return route.fulfill({ status: 503, json: {} }) })
  await page.route('**/api/v1/pfd*', route => { requests.push(new URL(route.request().url())); return route.fulfill({ json: { totals: { reports: 1, with_concerns: 0, stubs: 1 }, mentions: { sent_to_providers: 2, naming_providers: 1, recipient_organisations: 2 }, recent: [{ report_ref: '2026-0001', report_date: null, has_concerns: false, source_url: 'https://example.invalid/pfd', retrieved_at: '2026-09-01' }], by_year: [], by_coroner_area: [], concern_terms: [], caveats: {}, sar: { totals: { documents: 1, with_text: 0, with_board_name: 0 }, mentions: { naming_providers: 0 }, recent: [{ document_url: 'https://example.invalid/sar', source_url: 'https://example.invalid/library', library_year: 2025, sab_name: null, has_body_text: 0 }], by_year: [{ year: 2025, documents: 1, with_text: 0 }], by_board: [], concern_terms: [{ term: '<script>unsafe</script>', occurrences: 0 }], caveats: {} } } }) })
  await page.goto('/#/pfd?lens=sar&source=pfd&relationship=addressed_to&provider_key=example-recovery&year_from=2020')
  await expect(page.getByText('Unfiltered source collection.', { exact: false })).toBeVisible()
  const years = page.getByRole('region', { name: 'Documents by library year, not report date', exact: true })
  await expect(years.getByRole('cell', { name: '2025', exact: true })).toBeVisible()
  expect(requests[0]!.search).toBe('')
  expect(eventRequests).toBe(0)
  await expect(page.getByRole('cell', { name: '<script>unsafe</script>', exact: true })).toBeVisible()
  expect(await page.locator('script').evaluateAll(nodes => nodes.some(node => node.textContent === 'unsafe'))).toBe(false)
  const collection = page.getByRole('region', { name: 'SAR library records', exact: true })
  await collection.getByRole('button', { name: /Inspect https:/ }).click()
  await expect(page.getByRole('complementary', { name: 'https://example.invalid/sar', exact: true })).toContainText('Library year is not a report date')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog').getByText('2025', { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('safety-sar-mobile.png'), animations: 'disabled' })
  await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'PFD report collection', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Metadata stub without concern text', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download all held PFD reports CSV', exact: true })).toHaveAttribute('href', '/api/v1/export?endpoint=pfd&format=csv')
  await page.getByRole('button', { name: 'HSE register records', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Withdrawn following appeal', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Inspect N-1, displayed row 1', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('2025-04-01', { exact: true })).toBeVisible()
  await expect(page.getByRole('dialog').getByText('2025-05-01', { exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Source chronology', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Evidence is unavailable' })).toBeVisible()
  await page.getByRole('button', { name: 'SAR library collection', exact: true }).click()
  await expect(years.getByRole('cell', { name: '2025', exact: true })).toBeVisible()
})

test('safety refuses ambiguous selections and unsupported filters without substituting records', async ({ page }) => {
  let requests = 0
  const row = event('hse', '2026-01-01', 'matched_to', 'Duplicate returned notice')
  const identity = JSON.stringify(['hse-events', row.source, row.relationship, row.entity_type, row.entity_key, row.title, row.date, row.source_url])
  await page.route('**/api/v1/safety_legal*', route => { requests++; return route.fulfill({ json: { events: [row, row], truncated: false, caveats: {} } }) })
  await page.goto(`/#/pfd?${new URLSearchParams({ source: 'hse', safety_lane: 'hse-events', safety_record: identity })}`)
  await expect(page.getByRole('complementary', { name: 'Source record unavailable or ambiguous' })).toBeVisible()
  await expect(page.getByText('No replacement has been selected.', { exact: false })).toBeVisible()
  await page.goto('/#/pfd?source=unsupported')
  await expect(page.getByText('The selected source is not supported.', { exact: false })).toBeVisible()
  expect(requests).toBe(1)
})
