import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
const statement = { id: 17, claim_text: 'Published text <script>unsafe</script> — retained; exactly.', created_by: 'Campaign author', created_at: '2025-01-02', published_by: null, published_at: null, note: 'Author note', caveats: ['Original caveat — retained; exactly.'], citations: [{ table: 'source_table', key: 'key/1', resolved: { label: 'Published source label', url: 'https://example.invalid/evidence', source_url: 'https://example.invalid/raw', retrieved_at: '2024-08-03' } }, { table: 'older_source', key: 'missing/key', resolved: null }] }
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://localhost:4173') throw new Error(`Unexpected external request: ${url.origin}`)
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/map/')) return route.fulfill({ status: 503, json: { error: 'No fixture for this request' } })
    return route.continue()
  })
})

test('statements retain authorship, unresolved citations and exact exported source text', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  let requests = 0
  await page.route('**/api/v1/claims*', route => { requests++; expect(new URL(route.request().url()).search).toBe(''); return route.fulfill({ json: { claims: [statement], caveat: 'Campaign-authored statement caveat.' } }) })
  await page.goto('/#/claims?provider_key=retained&year_from=2020')
  await expect(page.getByRole('searchbox', { name: 'Statement text or identifier' })).toHaveCSS('border-top-style', 'solid')
  const article = page.getByRole('article', { name: 'Campaign statement 17' })
  await expect(article.getByText(statement.claim_text, { exact: true })).toBeVisible()
  await expect(article).toContainText('Publication approved by not supplied. Published: not supplied.')
  await expect(article).toContainText('1 unresolved or without resolution data.')
  await article.getByRole('button').click()
  const inspector = page.getByRole('complementary', { name: 'Campaign statement 17' })
  await expect(inspector).toBeVisible()
  await inspector.getByRole('button', { name: 'Inspect citation 1', exact: true }).click()
  await expect(inspector.getByRole('link', { name: 'Open cited evidence' })).toHaveAttribute('href', 'https://example.invalid/evidence')
  await inspector.getByText('Source details', { exact: true }).click()
  await expect(inspector.getByText('2024-08-03', { exact: true })).toBeVisible()
  await expect(inspector).toContainText('The citation response does not include a payload hash.')
  await inspector.getByRole('button', { name: 'Inspect citation 2', exact: true }).click()
  await expect(inspector.getByRole('region', { name: 'Selected statement citation' })).toContainText('missing/key')
  await expect(page).toHaveURL(/citation=/)
  await page.reload()
  await expect(inspector.getByRole('region', { name: 'Selected statement citation' })).toContainText('Unresolved citation.')
  const download = page.waitForEvent('download')
  await inspector.getByRole('button', { name: 'Download statement with citations JSON' }).click()
  const file = JSON.parse(readFileSync((await (await download).path())!, 'utf8'))
  expect(file.rows).toEqual([statement])
  expect(file._provenance.request_filters).toEqual({})
  expect(file._provenance.caveat).toBe('Campaign-authored statement caveat.')
  await inspector.getByRole('button', { name: 'Save statement reference' }).click()
  await expect(inspector.getByText('Statement reference saved', { exact: false })).toBeVisible()
  expect(requests).toBe(2)
  expect(await page.locator('script').evaluateAll(nodes => nodes.some(node => node.textContent === 'unsafe'))).toBe(false)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: info.outputPath('statement-citations-desktop.png'), fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('dialog', { name: 'Campaign statement 17' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('statement-citations-mobile.png'), animations: 'disabled' })
  await page.getByRole('dialog', { name: 'Campaign statement 17' }).getByRole('button', { name: 'Close', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('combobox', { name: 'Colour theme' }).selectOption('light')
  await expect(page.getByRole('searchbox', { name: 'Statement text or identifier' })).toHaveCSS('border-top-color', 'rgb(118, 118, 118)')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: info.outputPath('statements-light.png'), fullPage: true, animations: 'disabled' })
})

test('local statement search and pages retain selected identities without refetching', async ({ page }) => {
  let requests = 0
  const claims = Array.from({ length: 24 }, (_, index) => ({ ...statement, id: index + 1, claim_text: `Statement content ${index + 1}`, citations: [], caveats: [] }))
  await page.route('**/api/v1/claims*', route => { requests++; return route.fulfill({ json: { claims, caveat: null } }) })
  await page.goto('/#/claims?claim=1')
  await expect(page.getByRole('article')).toHaveCount(20)
  await page.getByRole('navigation', { name: 'Statement display pages' }).getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(4)
  await expect(page.getByRole('complementary', { name: 'Campaign statement 1' })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Statement text or identifier' }).fill('Statement content 23')
  await expect(page.getByRole('article')).toHaveCount(4)
  await page.getByRole('button', { name: 'Search statements', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(1)
  await expect(page).toHaveURL(/q=Statement/)
  expect(requests).toBe(1)
  await page.reload()
  await expect(page.getByRole('article', { name: 'Campaign statement 23' })).toBeVisible()
  await expect(page.getByRole('complementary', { name: 'Campaign statement 1' })).toBeVisible()
})

test('missing arrays and ambiguous statement or citation identifiers are explicit', async ({ page }) => {
  const citation = { table: 'same', key: 'same', resolved: null }
  await page.route('**/api/v1/claims*', route => route.fulfill({ json: { claims: [{ ...statement, citations: [citation, citation] }, { ...statement, id: 22, citations: null, caveats: null }, { ...statement, id: 33 }, { ...statement, id: '33' }], caveat: null } }))
  await page.goto(`/#/claims?${new URLSearchParams({ claim: '17', citation: JSON.stringify(['same', 'same']) })}`)
  await expect(page.getByText('The saved table and key do not identify one citation', { exact: false })).toBeVisible()
  await expect(page.getByRole('article', { name: 'Campaign statement 22' })).toContainText('Citation array not supplied.')
  await page.goto('/#/claims?claim=33')
  await expect(page.getByRole('complementary', { name: 'Statement unavailable or ambiguous' })).toBeVisible()
  await page.goto('/#/claims?claim=missing')
  await expect(page.getByText('The requested statement identifier missing', { exact: false })).toBeVisible()
  await page.route('**/api/v1/claims*', route => route.fulfill({ json: { caveat: null } }))
  await page.reload()
  await expect(page.getByText('The published statement array was not supplied.', { exact: false })).toBeVisible()
  await page.route('**/api/v1/claims*', route => route.fulfill({ status: 503, json: {} }))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Evidence is unavailable' })).toBeVisible()
  await page.route('**/api/v1/claims*', route => route.fulfill({ json: { claims: [], caveat: null } }))
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'No published statements match this search' })).toBeVisible()
})
