import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
const response = { found: true, hops: 1, max_hops: 6, verified_only: true, note: 'Synthetic reviewed path note.', nodes: [{ node: 'provider:graph-only', type: 'provider', id: 'public-provider', label: 'Example Provider' }, { node: 'authority:graph-only', type: 'authority', id: 'E00000001', label: 'Example Authority' }], path: [{ from: 'provider:graph-only', to: 'authority:graph-only', relationship: 'awarded_contract_to', relationship_label: 'awarded a contract to', basis: 'supplier_alias_confirmed', source_url: 'https://example.invalid/edge', retrieved_at: '2026-09-01' }] }
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://localhost:4173') throw new Error(`Unexpected external request: ${url.origin}`)
    if (url.pathname === '/api/v1/providers') return route.fulfill({ json: { providers: [{ provider_key: 'public-provider', canonical_name: 'Example Provider' }] } })
    if (url.pathname === '/api/v1/authorities') return route.fulfill({ json: { authorities: [{ ons_code: 'E00000001', name: 'Example Authority' }] } })
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/map/')) return route.fulfill({ status: 503, json: { error: 'No fixture' } })
    return route.continue()
  })
})
test('verified path submits endpoints, preserves evidence and exports an inspectable sequence', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  const requests: URL[] = []
  await page.route('**/api/v1/relationship_path?*', route => { requests.push(new URL(route.request().url())); return route.fulfill({ json: response }) })
  await page.goto('/#/pathfinder?year_from=2025')
  await expect(page.getByLabel('Location', { exact: true })).toContainText('Connections')
  await expect(page.getByRole('navigation', { name: 'Main sections', exact: true }).getByRole('link', { name: 'Connections', exact: true })).toHaveClass(/router-link-active/)
  await page.getByRole('combobox', { name: 'Start provider', exact: true }).selectOption('public-provider')
  await page.getByRole('combobox', { name: 'End authority', exact: true }).selectOption('E00000001')
  expect(requests).toHaveLength(0)
  await page.getByRole('button', { name: 'Find verified path', exact: true }).click()
  const diagram = page.getByRole('region', { name: 'Verified path diagram', exact: true })
  await expect(diagram).toBeVisible()
  expect(Object.fromEntries(requests[0]!.searchParams)).toEqual({ from_type: 'provider', from_id: 'public-provider', to_type: 'authority', to_id: 'E00000001', max_hops: '6' })
  await expect(page.getByText('Original edge direction is not returned', { exact: false }).first()).toBeVisible()
  const png = page.waitForEvent('download')
  await diagram.getByRole('button', { name: 'Download annotated path PNG' }).click()
  await (await png).saveAs(info.outputPath('verified-path.png'))
  const hop = diagram.getByRole('button', { name: 'Inspect diagram hop 1' })
  await hop.focus()
  await hop.press('Enter')
  await expect(hop).toHaveAttribute('aria-pressed', 'true')
  const inspector = page.getByRole('complementary', { name: 'Path hop 1', exact: true })
  await expect(inspector.getByRole('link', { name: 'Open hop start profile' })).toHaveAttribute('href', '#/providers/public-provider')
  await expect(inspector.getByRole('link', { name: 'Open hop end profile' })).toHaveAttribute('href', '#/authorities/E00000001')
  await expect(inspector).toContainText('supplier_alias_confirmed')
  const json = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download path reference JSON' }).click()
  expect(JSON.parse(readFileSync((await (await json).path())!, 'utf8')).rows).toEqual([response])
  expect(requests).toHaveLength(1)
  await page.reload()
  await expect(inspector).toBeVisible()
  await page.route('**/api/v1/relationship_path?*', route => route.fulfill({ json: { ...response, path: [{ ...response.path[0], basis: 'changed-basis' }] } }))
  await page.reload()
  await expect(inspector.getByText('The saved hop does not identify a returned record.', { exact: false })).toBeVisible()
  await expect(inspector.getByRole('link')).toHaveCount(0)
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('combobox', { name: 'Colour theme' }).selectOption('light')
  await expect(diagram.locator('svg g text').first()).toHaveAttribute('fill', '#070707')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: info.outputPath('verified-path-light.png'), fullPage: true, animations: 'disabled' })
})
test('saved path bounds, missing arrays and duplicate identities remain explicit', async ({ page }) => {
  let requests = 0
  await page.route('**/api/v1/relationship_path?*', route => { requests++; return route.fulfill({ json: { ...response, nodes: [...response.nodes, response.nodes[0]] } }) })
  await page.goto('/#/pathfinder?from_id=a&to_id=b&max_hops=8')
  await expect(page.getByText('Choose a hop bound from 1 to 6.', { exact: false })).toBeVisible()
  expect(requests).toBe(0)
  await page.getByRole('combobox', { name: 'Maximum hops' }).selectOption('6')
  await page.getByRole('button', { name: 'Find verified path' }).click()
  await page.getByRole('button', { name: 'Inspect hop 1', exact: true }).click()
  const inspector = page.getByRole('complementary', { name: 'Path hop 1', exact: true })
  await expect(inspector.getByRole('link', { name: 'Open hop start profile' })).toHaveCount(0)
  await inspector.getByRole('button', { name: 'Close', exact: true }).click()
  await page.route('**/api/v1/relationship_path?*', route => route.fulfill({ json: { ...response, path: null } }))
  await page.reload()
  await expect(page.getByText('The path array was not supplied.', { exact: false })).toBeVisible()
})
test('mobile path uses the evidence list and can retry a bounded no-path response', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/pathfinder?from_type=supplier&from_id=supplier-key&to_id=E00000001')
  await expect(page.getByRole('heading', { name: 'Evidence is unavailable' })).toBeVisible()
  await page.route('**/api/v1/relationship_path?*', route => route.fulfill({ json: { found: false, max_hops: 6, verified_only: true, reason: 'Synthetic search space limit.' } }))
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'No verified path returned' })).toBeVisible()
  await expect(page.getByText('Synthetic search space limit.')).toBeVisible()
  await page.route('**/api/v1/relationship_path?*', route => route.fulfill({ json: response }))
  await page.reload()
  await expect(page.getByRole('button', { name: 'Data', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('region', { name: 'Verified path diagram', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Inspect hop 1', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Path hop 1', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('verified-path-mobile.png'), animations: 'disabled' })
})
