<script setup lang="ts">
import type { ConnectionDetail } from '~/types/connections'
import { connectionText } from '~/lib/connections'
import { downloadEvidenceJson } from '~/lib/evidence-export'
const props = defineProps<{ id: string }>()
const emit = defineEmits<{ centre: [query: { ons_code?: string; provider_key?: string }] }>()
const api = usePublicApi()
const route = useRoute()
const filters = useFilterState()
const { data, pending, error, refresh } = await useAsyncData(() => `public-connection-detail-${props.id}`, (_app, { signal }) => api.get<ConnectionDetail>(`/relationships/${encodeURIComponent(props.id)}`, { signal }))
const current = computed(() => data.value?.relationship_id === props.id ? data.value : null)
const rows = computed(() => Array.isArray(current.value?.timeline) ? current.value.timeline : null)
const offset = computed(() => { const value = Number(filters.get('timeline_offset') ?? 0); return Number.isSafeInteger(value) && value >= 0 ? value : 0 })
const displayed = computed(() => (rows.value ?? []).slice(offset.value, offset.value + 25))
function download() { if (current.value) downloadEvidenceJson(`commissioning-${props.id}-returned-history`, [current.value], { scope: 'returned-pair-history', endpoint: `/api/v1/relationships/${encodeURIComponent(props.id)}`, request_filters: {}, response_truncated: current.value.truncated ?? null, caveat: current.value.caveat ?? null, retained_view: `#${route.fullPath}`, limitations: 'The history covers the authority/provider pair, not only the selected edge. Rows can repeat an edge when several source notices match. Notice links are constructed by the API. Payload hashes and per-edge derivation types are not returned.' }) }
</script>
<template>
  <section class="space-y-4" aria-label="Supporting commissioning history"><h3>Supporting authority/provider history</h3><StEvidenceState :pending="pending" :error="error" @retry="refresh"><p v-if="!current" role="status">The detail response does not identify the selected relationship. No other history has been substituted.</p><template v-else><p>Relationship type: {{ current.predicate ?? 'not supplied' }}.</p><p class="atlas-footnote">This history covers returned edges between the same authority and provider. Several notice matches can repeat an edge. It is not an award count or a current service-delivery record.</p><p class="atlas-caveat">{{ current.caveat ?? 'The response supplied no additional history caveat.' }}</p>
    <section aria-label="Supplied authority identity"><h4>Authority: {{ current.authority?.name ?? 'not supplied' }}</h4><p class="atlas-footnote">Graph identifier: {{ current.authority?.entity_id ?? 'not supplied' }}. ONS code: {{ current.authority?.ons_code ?? 'not supplied' }}.</p><div v-if="current.authority?.ons_code" class="st-inspector-actions"><NuxtLink :to="`/authorities/${encodeURIComponent(current.authority.ons_code)}`" class="atlas-button">Open authority profile</NuxtLink><button type="button" class="atlas-button" @click="emit('centre', { ons_code: current.authority.ons_code })">Centre on this authority</button></div></section>
    <section aria-label="Supplied provider identity"><h4>Provider: {{ current.provider?.name ?? 'not supplied' }}</h4><p class="atlas-footnote">Graph identifier: {{ current.provider?.entity_id ?? 'not supplied' }}. Provider key: {{ current.provider?.provider_key ?? 'not supplied' }}.</p><div v-if="current.provider?.provider_key" class="st-inspector-actions"><NuxtLink :to="`/providers/${encodeURIComponent(current.provider.provider_key)}`" class="atlas-button">Open provider profile</NuxtLink><button type="button" class="atlas-button" @click="emit('centre', { provider_key: current.provider.provider_key })">Centre on this provider</button></div></section>
    <NuxtLink v-if="current.authority?.ons_code && current.provider?.provider_key" :to="{ path: '/contracts', query: { buyer_ons_code: current.authority.ons_code, provider_key: current.provider.provider_key } }" class="atlas-button">Explore notices for this supplied pair</NuxtLink>
    <p v-if="current.truncated" class="atlas-caveat">The history was truncated at 500 returned rows. The download covers this bounded response.</p><p v-else-if="current.truncated == null">History truncation status was not supplied.</p><p v-if="!rows" role="status">The history array was not supplied.</p><p v-else-if="!rows.length">No supporting history rows were returned.</p><template v-else><p class="atlas-footnote">{{ rows.length }} returned history rows. {{ displayed.length }} displayed in response order. Validity dates and notice publication dates remain separate.</p><ol class="st-connection-history" :start="offset + 1"><li v-for="(event, index) in displayed" :key="index"><h4>{{ event.notice?.title ?? event.relationship_id ?? 'Record label not supplied' }}</h4><p>Relationship identifier: {{ event.relationship_id ?? 'not supplied' }}.</p><p>Valid from: {{ event.valid_from ?? 'not supplied' }}. Valid to: {{ event.valid_to ?? 'not supplied' }}.</p><p>Recorded confidence: {{ event.confidence ?? 'not supplied' }}.</p><h5>Relationship evidence</h5><StProvenance :provenance="event" /><template v-if="event.notice"><h5>Matched notice</h5><dl><template v-for="field in ['notice_id', 'date_published', 'buyer_name', 'supplier_name_raw', 'value_core', 'currency']" :key="field"><dt>{{ field.replaceAll('_', ' ') }}</dt><dd>{{ connectionText(event.notice[field]) }}</dd></template></dl><p class="atlas-footnote">The value is a notice-stage estimate in the supplied currency. It is not a payment.</p><StProvenance :provenance="event.notice" /><StLink v-if="typeof event.notice.notice_web_url === 'string'" :href="event.notice.notice_web_url">Open constructed notice link</StLink><p class="atlas-footnote">This notice link is constructed by the API. The source URL above identifies the cited data.</p></template><p v-else>The notice is not available in this response. The relationship evidence remains visible.</p></li></ol><nav class="flex flex-wrap gap-2" aria-label="Supporting history display pages"><button type="button" class="atlas-button" :disabled="!offset" @click="filters.set('timeline_offset', String(Math.max(0, offset - 25)))">Previous history</button><button type="button" class="atlas-button" :disabled="offset + 25 >= rows.length" @click="filters.set('timeline_offset', String(offset + 25))">Next history</button><button v-if="offset" type="button" class="atlas-button" @click="filters.set('timeline_offset', undefined)">First history page</button></nav></template><p class="atlas-footnote">Neither relationship evidence nor matched notices include payload hashes in this response. Per-edge derivation types and source-system labels are not returned by the history endpoint.</p><button type="button" class="atlas-button" @click="download">Download returned pair history JSON</button>
  </template></StEvidenceState></section>
</template>
<style scoped>.st-connection-history { padding-left: 20px; } li { margin: 20px 0; border-top: 1px solid var(--border-subtle); padding-top: 16px; overflow-wrap: anywhere; } dt { color: var(--text-muted); font-size: 12px; margin-top: 8px; } dd { overflow-wrap: anywhere; } h4, h5 { font-weight: 600; margin-top: 12px; } </style>
