<script setup lang="ts">
import { payCell, payRecordKey, type PayLens, type PayRow } from '~/lib/pay-lenses'
import { downloadEvidenceCsv, downloadEvidenceJson } from '~/lib/evidence-export'
const props = defineProps<{ lens: PayLens; rows: PayRow[]; query: Record<string, string | undefined>; caveats: Record<string, string | null> }>()
const filters = useFilterState()
const route = useRoute()
const notebook = useNotebook()
const status = ref('')
const selection = computed(() => String(filters.get('record') ?? ''))
const chartView = computed(() => props.lens.key === 'adverts' && filters.get('pay_view') !== 'data')
const offset = computed(() => { const value = Number(filters.get('pay_offset') ?? 0); return Number.isSafeInteger(value) && value >= 0 ? value : 0 })
const displayed = computed(() => props.rows.slice(offset.value, offset.value + 25))
const candidates = computed(() => selection.value ? props.rows.filter(row => payRecordKey(props.lens, row) === selection.value) : [])
const selected = computed(() => candidates.value.length === 1 ? candidates.value[0] : undefined)
const mainTitle = (row: PayRow) => String(row[props.lens.columns[0]!.key] ?? 'Published observation')
let trigger: HTMLElement | null = null
async function inspect(row: PayRow, event?: Event) { trigger = (event?.currentTarget ?? document.activeElement) as HTMLElement | null; await filters.set('record', payRecordKey(props.lens, row)); await nextTick(); document.querySelector<HTMLElement>('.st-inspector-heading')?.focus() }
async function close() { await filters.set('record', undefined); await nextTick(); if (trigger?.isConnected) trigger.focus() }
function page(delta: number) { return filters.set('pay_offset', String(Math.max(0, offset.value + delta))) }
function context() { return { scope: 'displayed-page-of-returned-array', endpoint: '/api/v1/pay', array: props.lens.array, filters_applied_to_this_lens: props.query, canonical_query: `/api/v1/pay?${new URLSearchParams(Object.entries(props.query).filter((pair): pair is [string, string] => pair[1] !== undefined))}`, retained_view: `#${route.fullPath}`, returned_array_rows: props.rows.length, local_offset: offset.value, definition: props.lens.description, caveats: props.caveats, field_notes: props.lens.key === 'census' ? { source_page: 'Exports retain the source’s zero-based page index. The on-screen Source page is one higher for PDF readers.' } : {}, csv_notes: 'CSV prefixes formula-like text with an apostrophe. Numeric negatives stay numeric. JSON retains original values.' } }
const chartAnnotation = computed(() => `Scope: ${displayed.value.length} displayed rows of ${props.rows.length} returned adverts, starting at local offset ${offset.value}. Filters applied: ${JSON.stringify(props.query)}. ${props.lens.description} ${Object.values(props.caveats).filter(Boolean).join(' ')} Application view: ${import.meta.client ? window.location.origin + window.location.pathname : ''}#${route.fullPath}. Source URLs and retrieval dates are retained in the displayed rows JSON. This response does not supply advert payload hashes.`)
function download() { downloadEvidenceJson(`pay-${props.lens.key}-displayed-rows`, displayed.value, context()) }
function references() {
  const fields = ['source_url', 'retrieved_at', 'payload_sha256', 'content_sha256', 'source_system', 'advert_url', 'page_url', 'written_statement_url', 'source_page', 'financial_year_end', 'posted_date', 'closing_date', 'effective_from', 'period_label', 'reporting_year', 'reporting_year_label', 'census_year', 'time', 'year', 'salary_period', 'unit_of_measure', 'unit']
  const rows = displayed.value.map(row => ({ title: mainTitle(row), record_identifiers: Object.fromEntries(props.lens.identity.map(key => [key, row[key] ?? null])), ...Object.fromEntries(fields.map(key => [key, row[key] ?? null])) }))
  downloadEvidenceJson(`pay-${props.lens.key}-displayed-rows.provenance`, rows, { ...context(), manifest_for: `pay-${props.lens.key}-displayed-rows`, missing_metadata: 'Null means not supplied for this observation. No later source response has been attached to it.' })
}
function save() {
  if (!selected.value) return
  status.value = notebook.add({ title: `${props.lens.title}: ${mainTitle(selected.value)}`, href: `#${route.fullPath}`, note: JSON.stringify({ record: selected.value, ...context(), scope: 'selected-returned-observation' }, null, 2) }) ? 'Evidence reference saved to this browser’s notebook.' : 'This browser could not save the reference.'
}
watch(selection, () => { status.value = '' })
const extraFields = computed(() => selected.value ? Object.entries(selected.value).filter(([key]) => !props.lens.columns.some(column => column.key === key) && !['source_url', 'retrieved_at', 'payload_sha256', 'content_sha256'].includes(key)) : [])
function extraValue(value: unknown) { return value == null ? 'Not supplied' : typeof value === 'object' ? JSON.stringify(value) : String(value) }
</script>
<template>
  <section class="space-y-4"><p class="atlas-footnote">Returned observations: {{ rows.length }} · Displayed observations: {{ displayed.length }}. Pagination changes only the display of this returned array.</p><div class="flex flex-wrap gap-2" role="group" aria-label="Displayed pay evidence exports"><button type="button" class="atlas-button" @click="download">Download displayed rows JSON</button><button type="button" class="atlas-button" @click="downloadEvidenceCsv(`pay-${lens.key}-displayed-rows`, displayed)">Download displayed rows CSV</button><button type="button" class="atlas-button" @click="references">Download reference manifest</button></div><p class="atlas-footnote">Each download covers {{ displayed.length }} displayed observations. Keep the reference manifest with the CSV or chart. CSV protects formula-like text for spreadsheets. JSON retains the original values.</p>
    <div v-if="lens.key === 'adverts'" class="flex flex-wrap gap-2" role="group" aria-label="Advert presentation"><button type="button" class="atlas-button" :aria-pressed="chartView" @click="filters.set('pay_view', 'chart')">Chart</button><button type="button" class="atlas-button" :aria-pressed="!chartView" @click="filters.set('pay_view', 'data')">Data</button></div>
    <div class="st-directory-workspace" :class="{ 'has-inspector': selection }"><div class="min-w-0 space-y-4"><LazyStAdvertRangeChart v-if="chartView && displayed.length" :rows="displayed" :lens="lens" :selected="selection" :annotation="chartAnnotation" @inspect="inspect" />
      <div v-if="displayed.length" class="overflow-x-auto" tabindex="0" role="region" :aria-label="`${lens.title} data`"><table class="w-full text-sm"><caption class="text-left atlas-footnote">{{ lens.title }}. Values retain the source’s periods and units.</caption><thead><tr><th v-for="column in lens.columns" :key="column.key" scope="col" class="p-2 text-left" :class="{ 'text-right': column.numeric }">{{ column.label }}</th><th scope="col" class="p-2">Inspect</th></tr></thead><tbody><tr v-for="(row, index) in displayed" :key="`${payRecordKey(lens, row)}:${index}`" :class="{ 'st-pay-selected': payRecordKey(lens, row) === selection }"><td v-for="column in lens.columns" :key="column.key" class="p-2 align-top" :class="{ 'text-right tabular-nums': column.numeric }"><NuxtLink v-if="column.key === 'canonical_name' && typeof row.provider_key === 'string'" :to="`/providers/${encodeURIComponent(row.provider_key)}`">{{ payCell(column, row) }}</NuxtLink><span v-else-if="row[column.key] == null || row[column.key] === ''"><span aria-hidden="true">—</span><span class="sr-only">Not supplied</span></span><span v-else>{{ payCell(column, row) }}</span></td><td class="p-2 align-top"><button class="atlas-button" type="button" :aria-label="`Inspect ${mainTitle(row)}, displayed row ${index + 1}`" @click="inspect(row, $event)">Inspect</button></td></tr></tbody></table></div>
      <StEvidenceState v-else empty :empty-title="offset ? 'No observations on this display page' : 'No observations returned for this question'" message="Check the active source filters and the coverage limitations. Missing records do not establish absence of activity." />
      <nav class="flex flex-wrap gap-3 items-center" :aria-label="`${lens.title} display pages`"><span class="atlas-footnote">{{ displayed.length ? `Rows ${offset + 1} to ${offset + displayed.length} of ${rows.length} returned` : 'No displayed rows' }}</span><button type="button" class="atlas-button" :disabled="!offset" @click="page(-25)">Previous</button><button type="button" class="atlas-button" :disabled="offset + displayed.length >= rows.length" @click="page(25)">Next</button><button v-if="offset" type="button" class="atlas-button" @click="filters.set('pay_offset', undefined)">First page</button></nav>
    </div><StInspector v-if="selection" :title="selected ? mainTitle(selected) : 'Observation unavailable or ambiguous'" @close="close"><template v-if="selected"><p class="atlas-footnote">{{ lens.title }}</p><dl class="st-pay-fields"><template v-for="column in lens.columns" :key="column.key"><dt>{{ column.label }}</dt><dd>{{ payCell(column, selected) }}</dd></template></dl><details v-if="extraFields.length"><summary>Other supplied record fields</summary><dl class="st-pay-fields"><template v-for="[key, value] in extraFields" :key="key"><dt>{{ key.replaceAll('_', ' ') }}</dt><dd>{{ extraValue(value) }}</dd></template></dl></details><StProvenance :provenance="selected" /><p class="atlas-footnote">{{ lens.description }}</p><div class="st-inspector-actions"><StLink v-if="typeof selected.advert_url === 'string'" :href="selected.advert_url" class="atlas-button">Open original advert</StLink><StLink v-if="typeof selected.page_url === 'string'" :href="selected.page_url" class="atlas-button">Open provider page</StLink><StLink v-if="typeof selected.written_statement_url === 'string'" :href="selected.written_statement_url" class="atlas-button">Open employer statement</StLink><StLink v-if="typeof selected.source_url === 'string'" :href="selected.source_url" class="atlas-button">Open source</StLink><NuxtLink v-if="typeof selected.provider_key === 'string'" :to="`/providers/${encodeURIComponent(selected.provider_key)}`" class="atlas-button">Open supplied provider profile</NuxtLink><button type="button" class="atlas-button" @click="save">Save evidence reference</button></div><p role="status">{{ status }}</p></template><p v-else>The saved source identifiers do not identify one observation in the returned array. The record may have changed or the identifier may be shared. No replacement observation has been selected.</p></StInspector></div>
  </section>
</template>
<style scoped>
th { color: var(--text-muted); font-weight: 500; }
td { border-bottom: 1px solid var(--border-subtle); min-width: 125px; max-width: 380px; overflow-wrap: anywhere; }
.st-pay-selected { background: var(--surface-elevated); }
.st-pay-fields { display: grid; grid-template-columns: minmax(90px, .8fr) minmax(0, 1.2fr); gap: 12px; margin: 16px 0; font-size: 13px; }
dt { color: var(--text-muted); }
dd { overflow-wrap: anywhere; }
</style>
