<script setup lang="ts">
import { treatmentObservation, treatmentText } from '~/lib/treatment'
import type { TreatmentObservation } from '~/types/treatment'
const props = defineProps<{ payload: Record<string, unknown>; peers: string[]; context: Record<string, unknown> }>()
const filters = useFilterState()
const route = useRoute()
const get = (key: string) => { const value = filters.get(key); return Array.isArray(value) ? value[0] ?? '' : value ?? '' }
const indicators = computed(() => Array.isArray(props.payload.indicators) ? props.payload.indicators as Record<string, unknown>[] : null)
const rows = computed(() => Array.isArray(props.payload.rows) ? props.payload.rows as Record<string, unknown>[] : null)
const chosen = computed(() => { const matches = (indicators.value ?? []).filter(row => row.indicator_id != null && String(row.indicator_id) === get('indicator')); return matches.length === 1 ? matches[0] : undefined })
const selectedRows = computed(() => chosen.value && rows.value ? rows.value.filter(row => row.indicator_id === chosen.value!.indicator_id) : null)
const england = computed(() => chosen.value && Array.isArray(props.payload.england) ? (props.payload.england as Record<string, unknown>[]).filter(row => row.indicator_id === chosen.value!.indicator_id) : null)
const view = computed(() => get('view') || 'chart')
const offset = computed(() => /^\d+$/.test(get('treatment_chart_offset')) ? Number(get('treatment_chart_offset')) : 0)
const peerRows = (peer: string) => (selectedRows.value ?? []).filter(row => row.ons_code === peer)
const observations = (peer: string) => peerRows(peer).slice(offset.value, offset.value + 12).map(row => treatmentObservation(row, 'local'))
const scope = computed(() => `treatment:${get('indicator')}`)
const sourceContext = computed(() => ({ ...props.context, selected_indicator: chosen.value ?? null, population_limitations: 'The comparison response exposes indicator definition, topic and substance, but no separate age or sex fields. No demographic slice can be inferred or selected here.', source_context: { ...props.payload, rows: undefined, england: undefined, indicators: undefined } }))
const selectedKey = computed(() => { const index = get('record_index'); if (get('record_scope') !== scope.value || !/^\d+$/.test(index)) return ''; const row = selectedRows.value?.[Number(index)]; return row && JSON.stringify(row) === get('record_snapshot') ? treatmentObservation(row, 'local').key : '' })
async function inspect(item: TreatmentObservation) { const index = selectedRows.value?.indexOf(item.row) ?? -1; if (index < 0) return; await filters.setAll({ ...filters.all(), record_scope: scope.value, record_index: String(index), record_snapshot: JSON.stringify(item.row) }); await nextTick(); document.querySelector<HTMLElement>('.st-inspector-heading')?.focus() }
const annotation = computed(() => `${JSON.stringify(sourceContext.value)}. Independent peer scales. At most 12 returned observations per peer in this chart group, offset ${offset.value}. View ${import.meta.client ? window.location.origin + window.location.pathname : ''}#${route.fullPath}`)
</script>
<template>
  <section class="space-y-5" aria-label="Treatment comparison"><p class="atlas-caveat">Choose one indicator before comparing observations. Its definition and unit determine what the figures describe. The response supplies no separate age or sex fields, so this view cannot select or infer a demographic subgroup.</p><p v-if="!indicators" role="status">The indicator catalogue was not supplied.</p><label v-else class="grid gap-2">Treatment indicator<select class="atlas-button" :value="get('indicator')" @change="filters.setAll({ ...filters.all(), indicator: ($event.target as HTMLSelectElement).value || undefined, treatment_chart_offset: undefined, record_scope: undefined, record_index: undefined, record_snapshot: undefined })"><option value="">Choose an indicator</option><option v-if="get('indicator') && !chosen" :value="get('indicator')">Unavailable or ambiguous saved indicator: {{ get('indicator') }}</option><option v-for="(indicator, index) in indicators" :key="index" :value="String(indicator.indicator_id ?? '')" :disabled="indicator.indicator_id == null">{{ treatmentText(indicator.indicator_name) }} ({{ treatmentText(indicator.indicator_id) }}) · {{ treatmentText(indicator.unit) }}</option></select></label>
    <p v-if="!chosen" role="status">Select one unambiguous returned indicator. No substitute has been selected.</p><template v-else><h4>{{ treatmentText(chosen.indicator_name) }}</h4><dl class="grid gap-3 md:grid-cols-2"><div v-for="field in ['definition', 'unit', 'topic', 'substance']" :key="field"><dt>{{ field }}</dt><dd>{{ treatmentText(chosen[field]) }}</dd></div></dl><details><summary>Indicator metadata and provenance</summary><pre>{{ JSON.stringify(chosen, null, 2) }}</pre><StProvenance :provenance="chosen" /><p>Indicator metadata provenance is separate from observation provenance.</p></details><div class="flex gap-2" role="group" aria-label="Treatment comparison presentation"><button type="button" class="atlas-button" :aria-pressed="view === 'chart'" @click="filters.set('view', 'chart')">Chart</button><button type="button" class="atlas-button" :aria-pressed="view === 'data'" @click="filters.set('view', 'data')">Data</button></div><p v-if="!['chart', 'data'].includes(view)" role="status">The saved presentation is unsupported. The data table remains available.</p>
    <p v-if="!chosen.unit" role="status">The indicator unit was not supplied. Charts are unavailable, while original observations remain inspectable.</p><template v-else-if="view === 'chart' && selectedRows"><p class="atlas-footnote">Each peer has an independent numeric scale. Compare exact values and published confidence bounds, not point heights across panels. Charts show up to 12 returned observations per peer. Repeated periods remain separate observations.</p><div class="grid gap-6 xl:grid-cols-2"><section v-for="peer in peers" :key="peer" class="min-w-0"><h4>{{ peer }}</h4><p v-if="!observations(peer).length" role="status">No observations for this peer in the current chart group.</p><NuxtErrorBoundary v-else><LazyStTreatmentChart :rows="observations(peer)" :title="`${peer} ${treatmentText(chosen.indicator_name)}`" :unit="String(chosen.unit)" :selected="selectedKey" :annotation="annotation" @inspect="inspect" /><template #error="{ clearError }"><p role="status">The chart is unavailable. Original observations remain in the table.</p><button type="button" class="atlas-button" @click="clearError">Retry chart</button></template></NuxtErrorBoundary><div class="flex flex-wrap gap-2"><button v-for="(item, index) in observations(peer)" :key="index" type="button" class="atlas-button" @click="inspect(item)">Inspect {{ peer }} observation {{ offset + index + 1 }}</button></div></section></div><nav class="flex gap-2" aria-label="Treatment comparison chart groups"><button type="button" class="atlas-button" :disabled="!offset" @click="filters.set('treatment_chart_offset', String(Math.max(0, offset - 12)))">Previous chart group</button><button type="button" class="atlas-button" :disabled="peers.every(peer => peerRows(peer).length <= offset + 12)" @click="filters.set('treatment_chart_offset', String(offset + 12))">Next chart group</button><button v-if="offset" type="button" class="atlas-button" @click="filters.set('treatment_chart_offset', undefined)">First chart group</button></nav></template>
    <p v-for="peer in peers.filter(peer => selectedRows && !peerRows(peer).length)" :key="peer" role="status">{{ peer }}: no returned observations for this indicator. This does not mean zero treatment activity.</p><StComparisonRecords :rows="selectedRows" :scope="scope" :title="`${treatmentText(chosen.indicator_name)} authority observations`" :context="sourceContext" />
    <details><summary>England reference observations</summary><p>England is returned once as a separate reference. Its rows omit confidence bounds, source URL, retrieval date and payload hash. Authority or indicator provenance is not substituted for these missing fields.</p><StComparisonRecords :rows="england" :scope="`${scope}:england`" title="England treatment reference" :context="{ ...sourceContext, population: 'England reference', missing_provenance: 'Confidence bounds, source URL, retrieval date and payload hash are not returned for England rows.' }" /></details></template>
  </section>
</template>
<style scoped>dt { color: var(--text-muted); } dd, pre { overflow-wrap: anywhere; white-space: pre-wrap; }</style>
