<script setup lang="ts">
import type { TreatmentLane, TreatmentObservation, TreatmentRow } from '~/types/treatment'
import { treatmentObservation, treatmentText } from '~/lib/treatment'
import { downloadEvidenceCsv, downloadEvidenceJson } from '~/lib/evidence-export'
const props = defineProps<{ rows: TreatmentRow[]; lane: TreatmentLane; title: string; unit: string | null; periods?: unknown; chartAllowed?: boolean; query: Record<string, string | undefined>; endpoint: string; caveats: Record<string, string | null> }>()
const route = useRoute()
const filters = useFilterState()
const notebook = useNotebook()
const status = ref('')
const observations = computed(() => props.rows.map(row => treatmentObservation(row, props.lane)))
const offsetKey = computed(() => `${props.lane}_offset`)
const offset = computed(() => { const value = Number(filters.get(offsetKey.value) ?? 0); return Number.isSafeInteger(value) && value >= 0 ? value : 0 })
const displayed = computed(() => observations.value.slice(offset.value, offset.value + 25))
const selection = computed(() => filters.get('treatment_lane') === props.lane ? String(filters.get('treatment_record') ?? '') : '')
const candidates = computed(() => selection.value ? observations.value.filter(row => row.key === selection.value) : [])
const selected = computed(() => candidates.value.length === 1 ? candidates.value[0] : undefined)
const chartView = computed(() => props.chartAllowed && filters.get(`${props.lane}_view`) !== 'data')
const arrayQuery = computed(() => props.lane === 'england' ? Object.fromEntries(Object.entries(props.query).filter(([key]) => key !== 'ons_code')) : props.query)
const displayCohort = computed(() => props.lane === 'estimates' ? filters.get('cohort') ?? null : null)
const columns = computed(() => props.lane === 'local' || props.lane === 'england' ? [['authority_name', 'Authority'], ['time_period', 'Observation period'], ['value', 'Published value'], ['lower_ci_95', 'Lower 95% bound'], ['upper_ci_95', 'Upper 95% bound'], ['value_note', 'Published note']] : [['dataset', 'Source table'], ['measure', 'Published measure'], ['age_group', 'Age group'], ['time_period', 'Observation period'], ['published_in', 'Publication edition'], ['value_text', 'Published value text'], ['value', 'Numeric value'], ['lower', 'Lower 95% bound'], ['upper', 'Upper 95% bound'], ['has_interval', 'Response interval flag']])
const periods = computed(() => {
  if (!Array.isArray(props.periods) || !displayed.value.length) return undefined
  const indices = displayed.value.map(row => (props.periods as unknown[]).indexOf(row.row.time_period))
  return indices.every(index => index >= 0) ? props.periods.slice(Math.min(...indices), Math.max(...indices) + 1) : undefined
})
let trigger: HTMLElement | null = null
async function inspect(row: TreatmentObservation, event?: Event) { trigger = (event?.currentTarget ?? document.activeElement) as HTMLElement | null; await filters.setAll({ ...filters.all(), treatment_lane: props.lane, treatment_record: row.key }); await nextTick(); document.querySelector<HTMLElement>('.st-inspector-heading')?.focus() }
async function close() { await filters.setAll({ ...filters.all(), treatment_lane: undefined, treatment_record: undefined }); await nextTick(); if (trigger?.isConnected) trigger.focus() }
function scope() { return { scope: 'displayed-page-of-returned-source-array', endpoint: `/api/v1/${props.endpoint}`, source_array: { local: 'series', england: 'england_series', estimates: 'estimates', context: 'other_rows' }[props.lane], filters_applied_to_this_array: arrayQuery.value, request_filters: props.query, canonical_query: `/api/v1/${props.endpoint}?${new URLSearchParams(Object.entries(props.query).filter((pair): pair is [string, string] => pair[1] !== undefined))}`, display_cohort: displayCohort.value, local_offset: offset.value, returned_rows_in_display_cohort: props.rows.length, displayed_rows: displayed.value.length, unit: props.unit, retained_view: `#${route.fullPath}`, caveats: props.caveats, provenance_limitations: props.lane === 'england' ? 'England rows do not include confidence bounds, source URL, retrieval date or hash. No local-row metadata has been attached.' : 'This response does not include a payload hash. Observation and publication periods remain separate.', csv_notes: 'CSV protects formula-like text. JSON preserves original values.' } }
const annotation = computed(() => `${props.title}. Displayed rows ${displayed.value.length} of ${props.rows.length} in this source and display cohort. Local offset ${offset.value}. Filters applied to this array ${JSON.stringify(arrayQuery.value)}. Display cohort ${String(displayCohort.value ?? 'none')}. ${Object.values(props.caveats).filter(Boolean).join(' ')} ${scope().provenance_limitations} Application view: ${import.meta.client ? window.location.origin + window.location.pathname : ''}#${route.fullPath}.`)
function download(kind: 'json' | 'csv' | 'references') {
  const name = `treatment-${props.lane}-displayed-rows`
  const rows = displayed.value.map(item => item.row)
  if (kind === 'csv') downloadEvidenceCsv(name, rows)
  else if (kind === 'json') downloadEvidenceJson(name, rows, scope())
  else downloadEvidenceJson(`${name}.provenance`, displayed.value.map(item => ({ record_identity: item.key, label: item.label, source_url: item.row.source_url ?? null, retrieved_at: item.row.retrieved_at ?? null, payload_sha256: item.row.payload_sha256 ?? null, observation_period: item.row.time_period ?? null, publication_edition: item.row.published_in ?? null, age_group: item.row.age_group ?? null, value_text: item.row.value_text ?? null, value: item.value, lower: item.lower, upper: item.upper, interval_note: item.intervalNote })), scope())
}
function save() { if (selected.value) status.value = notebook.add({ title: `${props.title}: ${selected.value.period}`, href: `#${route.fullPath}`, note: JSON.stringify({ ...scope(), scope: 'selected-returned-observation', record: selected.value.row }, null, 2) }) ? 'Evidence reference saved to this browser’s notebook.' : 'This browser could not save the reference.' }
watch(selection, () => { status.value = '' })
</script>
<template>
  <section class="space-y-4" :aria-label="title"><h2>{{ title }}</h2><p class="atlas-footnote">{{ rows.length }} returned rows in this source and display cohort. {{ displayed.length }} displayed. Unit: {{ unit ?? 'not separately supplied by this response' }}.</p><p v-if="lane === 'england'" class="atlas-caveat">England values belong to this indicator but lack confidence bounds, source URL, retrieval date and hash in this response. Local-row provenance does not authenticate them.</p>
    <div class="flex flex-wrap gap-2" role="group" :aria-label="`${title} exports`"><button type="button" class="atlas-button" @click="download('json')">Download displayed rows JSON</button><button type="button" class="atlas-button" @click="download('csv')">Download displayed rows CSV</button><button type="button" class="atlas-button" @click="download('references')">Download reference manifest</button></div><p class="atlas-footnote">Keep the reference manifest with CSV or chart downloads. These files cover this displayed page, not other sources or unseen observations.</p>
    <div v-if="chartAllowed" class="flex gap-2" role="group" :aria-label="`${title} presentation`"><button type="button" class="atlas-button" :aria-pressed="chartView" @click="filters.set(`${lane}_view`, 'chart')">Chart</button><button type="button" class="atlas-button" :aria-pressed="!chartView" @click="filters.set(`${lane}_view`, 'data')">Data</button></div>
    <div class="st-directory-workspace" :class="{ 'has-inspector': selection }"><div class="min-w-0 space-y-4"><LazyStTreatmentChart v-if="chartView && displayed.length" :rows="displayed" :title="title" :unit="unit ?? 'Published value'" :periods="periods" :horizontal="lane === 'estimates'" :selected="selection" :annotation="annotation" @inspect="inspect" />
      <div v-if="displayed.length" class="overflow-x-auto" role="region" :aria-label="`${title} data`" tabindex="0"><table class="w-full text-sm"><caption class="text-left atlas-footnote">{{ title }}. Observation periods, publication editions and source notes remain distinct.</caption><thead><tr><th v-for="[key, label] in columns" :key="key" scope="col" class="p-2 text-left">{{ label }}</th><th scope="col" class="p-2 text-left">Uncertainty and source</th></tr></thead><tbody><tr v-for="(item, index) in displayed" :key="`${item.key}:${index}`" :class="{ 'st-treatment-selected': item.key === selection }"><td v-for="[key] in columns" :key="key" class="p-2 align-top" :class="{ 'text-right tabular-nums': ['value', 'lower', 'upper', 'lower_ci_95', 'upper_ci_95'].includes(key!) }"><span v-if="key === 'authority_name' && lane === 'england'">England</span><span v-else-if="item.row[key!] == null || item.row[key!] === ''"><span aria-hidden="true">—</span><span class="sr-only">Not supplied</span></span><span v-else>{{ treatmentText(item.row[key!]) }}</span></td><td class="p-2 align-top"><p class="atlas-footnote">{{ item.intervalNote }}</p><button type="button" class="atlas-button" :aria-label="`Inspect ${item.label}, ${item.period}, displayed row ${index + 1}`" @click="inspect(item, $event)">Inspect source</button></td></tr></tbody></table></div><StEvidenceState v-else empty :empty-title="offset ? 'No observations on this display page' : 'No observations returned for this source and selection'" />
      <nav class="flex flex-wrap gap-3 items-center" :aria-label="`${title} display pages`"><span class="atlas-footnote">{{ displayed.length ? `Rows ${offset + 1} to ${offset + displayed.length} of ${rows.length}` : 'No displayed rows' }}</span><button type="button" class="atlas-button" :disabled="!offset" @click="filters.set(offsetKey, String(Math.max(0, offset - 25)))">Previous</button><button type="button" class="atlas-button" :disabled="offset + displayed.length >= rows.length" @click="filters.set(offsetKey, String(offset + 25))">Next</button><button v-if="offset" type="button" class="atlas-button" @click="filters.set(offsetKey, undefined)">First page</button></nav>
    </div><StInspector v-if="selection" :title="selected ? `${selected.label}: ${selected.period}` : 'Observation unavailable or ambiguous'" @close="close"><template v-if="selected"><p>{{ title }}</p><p>{{ selected.intervalNote }}</p><dl class="st-treatment-fields"><template v-for="(value, key) in selected.row" :key="key"><dt>{{ String(key).replaceAll('_', ' ') }}</dt><dd>{{ treatmentText(value) }}</dd></template></dl><StProvenance :provenance="selected.row" /><p class="atlas-footnote">{{ scope().provenance_limitations }}</p><div class="st-inspector-actions"><StLink v-if="typeof selected.row.source_url === 'string'" :href="selected.row.source_url" class="atlas-button">Open original source</StLink><NuxtLink v-if="typeof selected.row.ons_code === 'string'" :to="`/authorities/${encodeURIComponent(selected.row.ons_code)}`" class="atlas-button">Open supplied authority profile</NuxtLink><button type="button" class="atlas-button" @click="save">Save evidence reference</button></div><p role="status">{{ status }}</p></template><p v-else>The saved source identifiers do not identify one observation in this returned source and display cohort. No replacement has been selected.</p></StInspector></div>
  </section>
</template>
<style scoped>
th { font-weight: 500; color: var(--text-muted); }
td { min-width: 120px; max-width: 350px; overflow-wrap: anywhere; border-bottom: 1px solid var(--border-subtle); }
.st-treatment-selected { background: var(--surface-elevated); }
.st-treatment-fields { display: grid; grid-template-columns: minmax(95px, .8fr) minmax(0, 1.2fr); gap: 12px; margin: 16px 0; font-size: 13px; }
dt { color: var(--text-muted); }
dd { overflow-wrap: anywhere; }
</style>
