<script setup lang="ts">
import { coMentionDestination, coMentionIdentity, coMentionKeyError, coMentionLimitations, type CoMentions } from '~/lib/co-mentions'
import { connectionText } from '~/lib/connections'
import { downloadEvidenceCsv, downloadEvidenceJson } from '~/lib/evidence-export'
const api = usePublicApi()
const filters = useFilterState()
const route = useRoute()
const notebook = useNotebook()
const get = (key: string) => { const value = filters.get(key); return Array.isArray(value) ? value[0] ?? '' : value ?? '' }
const keys = computed(() => { const raw = filters.get('key'); return raw ? Array.isArray(raw) ? raw : [raw] : [] })
const draft = ref(keys.value.length ? [...keys.value] : ['', ''])
const provider = ref('')
const signature = computed(() => JSON.stringify(keys.value))
watch(signature, () => { draft.value = keys.value.length ? [...keys.value] : ['', ''] })
const invalid = computed(() => coMentionKeyError(keys.value))
const draftError = ref('')
async function submit() { draftError.value = coMentionKeyError(draft.value); if (draftError.value) return; await filters.setAll({ ...filters.all(), key: [...draft.value], record: undefined, record_snapshot: undefined, offset: undefined }) }
function addProvider() { if (provider.value && (draft.value.length < 5 || draft.value.includes(''))) { const empty = draft.value.indexOf(''); if (empty >= 0) draft.value[empty] = provider.value; else draft.value.push(provider.value); provider.value = '' } }
const { data, pending, error, refresh } = await useAsyncData('public-co-mentions', async (_app, { signal }) => { if (invalid.value) return null; const key = signature.value; return { key, response: await api.get<CoMentions>('/cooccurrence', { query: { key: keys.value }, signal }) } }, { watch: [signature] })
const current = computed(() => data.value?.key === signature.value ? data.value.response : null)
const rows = computed(() => Array.isArray(current.value?.results) ? current.value.results : null)
const recordTypes = computed(() => [...new Set([...(current.value?.record_types ?? []), ...(rows.value ?? []).flatMap(row => row.record_type ? [row.record_type] : [])])])
const filtered = computed(() => (rows.value ?? []).filter(row => !get('record_type') || row.record_type === get('record_type')))
const offset = computed(() => /^\d+$/.test(get('offset')) ? Number(get('offset')) : 0)
const displayed = computed(() => filtered.value.slice(offset.value, offset.value + 25))
const selected = computed(() => { const matches = (rows.value ?? []).filter(row => coMentionIdentity(row) === get('record')); const row = matches.length === 1 ? matches[0] : undefined; return row && (!get('record_snapshot') || JSON.stringify(row) === get('record_snapshot')) ? row : undefined })
const status = ref('')
let trigger: HTMLElement | null = null
async function inspect(row: NonNullable<typeof rows.value>[number], event: Event) { trigger = event.currentTarget as HTMLElement; await filters.setAll({ ...filters.all(), record: coMentionIdentity(row), record_snapshot: JSON.stringify(row) }); await nextTick(); document.querySelector<HTMLElement>('.st-inspector-heading')?.focus() }
async function close() { await filters.setAll({ ...filters.all(), record: undefined, record_snapshot: undefined }); await nextTick(); if (trigger?.isConnected) trigger.focus() }
const scope = computed(() => ({ endpoint: '/api/v1/cooccurrence', selected_keys: keys.value, local_record_type: get('record_type') || null, local_offset: offset.value, limitations: coMentionLimitations, caveat: current.value?.caveat ?? null, api_note: current.value?.note ?? null, api_note_correction: 'The general API note claims all selected entities. That applies to document matching, while structured records can match two or more selected keys.', view: `#${route.fullPath}` }))
function download(kind: 'csv' | 'json' | 'references') { if (kind === 'csv') downloadEvidenceCsv('co-mentions-displayed-records', displayed.value); else downloadEvidenceJson(kind === 'references' ? 'co-mentions-returned-reference' : 'co-mentions-displayed-records', kind === 'references' ? [current.value] : displayed.value, { ...scope.value, scope: kind === 'references' ? 'complete-returned-bounded-response' : 'displayed-record-page' }) }
function save() { if (!selected.value) return; status.value = notebook.add({ title: selected.value.title ?? selected.value.record_id ?? 'Co-mention reference', href: `#${route.fullPath}`, note: JSON.stringify({ ...scope.value, record: selected.value }, null, 2) }) ? 'Record reference saved to this browser’s notebook.' : 'This browser could not save the reference.' }
useHead({ title: 'Mentioned together · SectorTrace' })
</script>
<template>
  <section class="space-y-6"><header class="st-page-header"><p class="atlas-eyebrow">Connections</p><h1>Mentioned together</h1><p>Records naming multiple selected organisations. Use the returned passages and matched fields to inspect what was actually recorded.</p></header><StConnectionsNav />
    <form class="space-y-4" @submit.prevent="submit"><div class="flex flex-wrap items-end gap-3"><StEntityPicker kind="provider" label="Add a provider from the directory" :model-value="provider" @update:model-value="provider = $event" /><button type="button" class="atlas-button" :disabled="!provider || (draft.length >= 5 && !draft.includes(''))" @click="addProvider">Add provider</button></div><div v-for="(_key, index) in draft" :key="index" class="flex flex-wrap items-end gap-3"><label>Organisation key {{ index + 1 }}<input v-model="draft[index]" autocomplete="off"></label><button type="button" class="atlas-button" :aria-label="`Remove organisation key ${index + 1}`" @click="draft.splice(index, 1)">Remove</button></div><p class="atlas-footnote">Use exact provider or supplier keys. Supplier keys can be copied from public evidence records. Names are not automatically resolved to identities.</p><div class="flex gap-3"><button type="button" class="atlas-button" :disabled="draft.length >= 5" @click="draft.push('')">Add another key</button><button type="submit" class="atlas-button">Find records</button></div><p v-if="draftError" role="status">{{ draftError }}</p></form>
    <p class="atlas-caveat">{{ coMentionLimitations }}</p><p v-if="get('provider_key') || get('ons_code') || get('year_from') || get('year_to')" class="atlas-footnote">Retained provider, authority and year filters do not filter this request. Only the submitted keys apply.</p>
    <p v-if="invalid" role="status">{{ invalid }}</p><StEvidenceState v-else :pending="pending" :error="error" @retry="refresh"><template v-if="current"><p class="atlas-caveat">{{ current.caveat ?? 'No source-specific caveat was supplied.' }}</p><details><summary>Returned API note and counting metadata</summary><p>The general API note below claims all selected entities. This is broader than the structured-record matching rule. Read each record’s returned matches.</p><p>{{ current.note ?? 'API note not supplied.' }}</p><pre>{{ connectionText(current.counts) }}</pre><p>These counts describe returned records by type, not sector-wide totals.</p></details>
    <h2>Selected key metadata</h2><ul v-if="Array.isArray(current.entities)" class="space-y-2"><li v-for="(entity, index) in current.entities" :key="index">{{ entity.name ?? 'Name not supplied' }} ({{ entity.key ?? 'Key not supplied' }}). Confirmed name variants: {{ connectionText(entity.variant_count) }}.<p v-if="entity.variant_count === 0" class="atlas-footnote">No confirmed document-search variants are held for this key. This does not establish an absence of mentions.</p></li></ul><p v-else role="status">Selected entity metadata was not supplied.</p>
    <p v-if="!rows" role="status">The result array was not supplied. This is not an empty result.</p><template v-else><p>{{ rows.length }} records returned within the 200-record cap. The response has no total-match count or truncation flag. Documents are collected first, so the cap can exclude later record types.</p><label>Record type<select :value="get('record_type')" @change="filters.setAll({ ...filters.all(), record_type: ($event.target as HTMLSelectElement).value || undefined, offset: undefined })"><option value="">All returned types</option><option v-if="get('record_type') && !recordTypes.includes(get('record_type'))" :value="get('record_type')">Unavailable saved type: {{ get('record_type') }}</option><option v-for="kind in recordTypes" :key="kind" :value="kind">{{ kind.replaceAll('_', ' ') }}</option></select></label><div class="flex flex-wrap gap-2"><button type="button" class="atlas-button" @click="download('csv')">Download displayed records CSV</button><button type="button" class="atlas-button" @click="download('json')">Download displayed records JSON</button><button type="button" class="atlas-button" @click="download('references')">Download returned reference JSON</button></div><p class="atlas-footnote">Displayed exports cover this local page. The returned reference contains the complete bounded API response and matching caveats. Keep it with the CSV.</p>
    <div class="st-inspector-layout" :class="{ 'has-inspector': !!get('record') }"><div class="space-y-4"><ul class="space-y-4" aria-label="Returned co-mention records"><li v-for="(row, index) in displayed" :key="index" class="st-mention"><h2>{{ row.title ?? row.record_id ?? 'Title not supplied' }}</h2><p>{{ row.record_type?.replaceAll('_', ' ') ?? 'Record type not supplied' }} · {{ row.source_system ?? 'Source system not supplied' }}</p><p>Record date: {{ row.date ?? 'Not supplied' }}</p><p v-if="row.text" class="whitespace-pre-wrap">{{ row.text }}</p><p v-if="row.record_type === 'document'" class="atlas-footnote">The returned excerpt is limited to 400 characters. Matching names can occur outside it. Open the document element for context.</p><dl v-if="row.matched && typeof row.matched === 'object'"><template v-for="(value, key) in row.matched" :key="key"><dt>{{ key }}</dt><dd>{{ connectionText(value) }}</dd></template></dl><p v-else class="atlas-footnote">Per-key matched fields were not supplied.</p><button v-if="coMentionIdentity(row)" type="button" class="atlas-button" @click="inspect(row, $event)">Inspect record {{ offset + index + 1 }}</button></li></ul><StEvidenceState v-if="!displayed.length" empty empty-title="No matching records on this page" message="This does not establish that the organisations are never mentioned together. Check the keys, confirmed variants and local record-type filter." /><nav aria-label="Co-mention result pages" class="flex gap-2"><button type="button" class="atlas-button" :disabled="!offset" @click="filters.set('offset', String(Math.max(0, offset - 25)))">Previous page</button><button type="button" class="atlas-button" :disabled="offset + 25 >= filtered.length" @click="filters.set('offset', String(offset + 25))">Next page</button><button v-if="offset" type="button" class="atlas-button" @click="filters.set('offset', undefined)">First page</button></nav></div>
    <StInspector v-if="get('record')" title="Co-mention record" @close="close"><template v-if="selected"><h3>{{ selected.title ?? selected.record_id }}</h3><dl><template v-for="(value, key) in selected" :key="key"><dt>{{ String(key).replaceAll('_', ' ') }}</dt><dd>{{ connectionText(value) }}</dd></template></dl><p class="atlas-caveat">This response does not provide the record’s source URL, retrieval date or payload hash. A record date is not a retrieval date.</p><NuxtLink v-if="coMentionDestination(selected)" :to="coMentionDestination(selected)!">{{ selected.record_type === 'document' ? 'Open document element' : 'Open supporting evidence explorer' }}</NuxtLink><p v-if="selected.record_type !== 'document'" class="atlas-footnote">The supporting explorer is a broader view. This response does not provide a verified direct record-selection link.</p><button type="button" class="atlas-button" @click="save">Save record reference</button><p role="status">{{ status }}</p></template><p v-else role="status">The saved selection is missing, ambiguous or changed. No replacement record has been selected.</p></StInspector></div>
    </template></template><p v-else role="status">The co-mention response was not supplied.</p></StEvidenceState>
  </section>
</template>
<style scoped>label { display: grid; gap: 6px; } input, select { min-height: 44px; padding: 8px; background: var(--surface-panel); color: var(--text-primary); border: 1px solid var(--border-control); border-radius: 4px; } .st-mention { padding: 16px; border: 1px solid var(--border-subtle); border-radius: 4px; } dt { color: var(--text-muted); margin-top: 10px; } dd, li, pre { overflow-wrap: anywhere; white-space: pre-wrap; }</style>
