<script setup lang="ts">
import type { ConnectionPayload } from '~/types/connections'
import { connectionName, connectionNode, connectionReferences, connectionText } from '~/lib/connections'
import { downloadEvidenceCsv, downloadEvidenceJson } from '~/lib/evidence-export'
const api = usePublicApi()
const route = useRoute()
const filters = useFilterState()
const notebook = useNotebook()
const get = (key: string) => { const value = filters.get(key); return Array.isArray(value) ? value[0] ?? '' : value ?? '' }
const query = computed(() => ({ ons_code: get('ons_code') || undefined, provider_key: get('provider_key') || undefined }))
const chosen = computed(() => Boolean(query.value.ons_code || query.value.provider_key))
const invalid = computed(() => query.value.ons_code && query.value.provider_key ? 'This view needs one centre. Choose an authority or a provider to resolve the mixed saved selection.' : query.value.ons_code && !/^[A-Z]\d{8}$/.test(query.value.ons_code) ? 'The authority identifier is not a supported ONS code.' : '')
const signature = computed(() => JSON.stringify(query.value))
const { data, pending, error, refresh } = await useAsyncData('public-commissioning-neighbourhood', async (_app, { signal }) => {
  if (!chosen.value || invalid.value) return null
  const key = signature.value
  return { key, response: await api.get<ConnectionPayload>('/relationships', { query: query.value, signal }) }
}, { watch: [signature] })
const current = computed(() => !pending.value && !error.value && data.value?.key === signature.value ? data.value.response : null)
const edges = computed(() => Array.isArray(current.value?.edges) ? current.value.edges : null)
const nodes = computed(() => [...(current.value?.center ? [current.value.center] : []), ...(Array.isArray(current.value?.neighbours) ? current.value.neighbours : [])])
const candidates = computed(() => get('relationship_id') ? (edges.value ?? []).filter(edge => edge.relationship_id === get('relationship_id')) : [])
const selected = computed(() => candidates.value.length === 1 ? candidates.value[0] : undefined)
const selectedNode = computed(() => connectionNode(nodes.value, get('node')))
const selectionConflict = computed(() => Boolean(get('relationship_id') && get('node')))
const hasInspector = computed(() => Boolean(get('relationship_id') || get('node')))
const name = (id: string | null | undefined) => connectionName(nodes.value, id)
const offsetFor = (key: string) => { const value = Number(get(key)); return Number.isSafeInteger(value) && value >= 0 ? value : 0 }
const offset = computed(() => offsetFor('offset'))
const diagramOffset = computed(() => offsetFor('diagram_offset'))
const displayed = computed(() => (edges.value ?? []).slice(offset.value, offset.value + 25))
const diagramRows = computed(() => (edges.value ?? []).slice(diagramOffset.value, diagramOffset.value + 12))
const wide = ref(false)
let media: MediaQueryList | undefined
function responsive() { wide.value = media?.matches ?? false }
onMounted(() => { media = matchMedia('(min-width: 900px)'); responsive(); media.addEventListener('change', responsive) })
onBeforeUnmount(() => media?.removeEventListener('change', responsive))
const view = computed(() => get('view') || (wide.value ? 'diagram' : 'data'))
const status = ref('')
let trigger: HTMLElement | SVGElement | null = null
let update = Promise.resolve()
function centre(value: { ons_code?: string; provider_key?: string }) {
  const next = update.then(() => filters.setAll({ ...filters.all(), ons_code: value.ons_code, provider_key: value.provider_key, relationship_id: undefined, node: undefined, offset: undefined, diagram_offset: undefined, timeline_offset: undefined }))
  update = next.catch(() => {})
  return next
}
async function inspect(id: string, event: Event, node = false) { trigger = event.currentTarget as HTMLElement | SVGElement; await filters.setAll({ ...filters.all(), relationship_id: node ? undefined : id, node: node ? id : undefined, timeline_offset: undefined }); await nextTick(); document.querySelector<HTMLElement>('.st-inspector-heading')?.focus() }
async function close() { await filters.setAll({ ...filters.all(), relationship_id: undefined, node: undefined, timeline_offset: undefined }); await nextTick(); if (trigger?.isConnected) trigger.focus() }
function scope(kind: string) { return { scope: kind, endpoint: '/api/v1/relationships', request_filters: query.value, predicate: 'AWARDED_TO', predicate_basis: 'This endpoint selects AWARDED_TO relationships only.', local_offset: offset.value, diagram_offset: diagramOffset.value, returned_edges: edges.value?.length ?? null, retained_view: `#${route.fullPath}`, caveat: current.value?.caveat ?? null, limitations: 'Per-edge derivation type and payload hash are not returned. Graph identifiers are not public provider keys or ONS codes. Validity dates do not establish current service delivery.' } }
const annotation = computed(() => `Source: /api/v1/relationships. AWARDED_TO edges only. Diagram group ${diagramRows.value.length} of ${edges.value?.length ?? 'unknown'} returned edges, offset ${diagramOffset.value}. Filters ${JSON.stringify(query.value)}. ${current.value?.caveat ?? ''} ${scope('diagram').limitations}\n${connectionReferences(diagramRows.value, nodes.value)}\nView ${import.meta.client ? window.location.origin + window.location.pathname : ''}#${route.fullPath}.`)
function download(kind: 'json' | 'csv' | 'references') {
  if (kind === 'csv') downloadEvidenceCsv('commissioning-displayed-edges', displayed.value)
  else if (kind === 'json') downloadEvidenceJson('commissioning-displayed-edges', displayed.value, scope('displayed-data-page'))
  else downloadEvidenceJson('commissioning-returned-references', [{ center: current.value?.center ?? null, neighbours: current.value?.neighbours ?? null, edges: edges.value }], scope('returned-neighbourhood-reference-manifest'))
}
function save() { const record = get('node') ? selectedNode.value : selected.value; if (record) status.value = notebook.add({ title: get('node') ? `Graph entity: ${name(get('node'))}` : `Commissioning relationship ${get('relationship_id')}`, href: `#${route.fullPath}`, note: JSON.stringify({ ...scope('selected-returned-record'), record }, null, 2) }) ? 'Connection reference saved to this browser’s notebook.' : 'This browser could not save the reference.' }
watch(() => [get('relationship_id'), get('node')], () => { status.value = '' })
useHead({ title: 'Commissioning connections · SectorTrace' })
</script>
<template>
  <section class="space-y-6"><header class="st-page-header"><p class="atlas-eyebrow">Connections</p><h1>Commissioning connections</h1><p>Authority-to-provider relationships supported by procurement evidence. Their dates do not establish current service delivery.</p></header><StConnectionsNav />
    <div class="flex flex-wrap gap-4"><StEntityPicker kind="authority" :model-value="get('ons_code')" @update:model-value="centre({ ons_code: $event || undefined })" /><StEntityPicker kind="provider" :model-value="get('provider_key')" @update:model-value="centre({ provider_key: $event || undefined })" /><button v-if="chosen" type="button" class="atlas-button" @click="centre({})">Clear centre</button></div><p v-if="get('year_from') || get('year_to')" class="atlas-footnote">Retained year bounds do not filter this endpoint. Each relationship retains its supplied validity dates.</p><p v-if="invalid" role="status">{{ invalid }}</p><p v-else-if="!chosen" role="status">Choose an authority or provider to inspect its commissioning neighbourhood.</p>
    <StEvidenceState v-else :pending="pending" :error="error" @retry="refresh"><template v-if="current"><h2>{{ current.center?.canonical_name ?? 'Centre name not supplied' }}</h2><p v-if="current.center?.entity_id === null" class="atlas-caveat">No graph entity is held for the selected organisation. This does not establish an absence of commissioning activity.</p><p class="atlas-caveat">{{ current.caveat ?? 'No source-specific caveat was supplied.' }}</p><p class="atlas-footnote">Only AWARDED_TO records are returned here. The response includes source facts and derived relationships but does not identify each row’s derivation type. Ownership, co-mentions and extracted claims are outside this view.</p><p v-if="!Array.isArray(current.neighbours)" role="status">The neighbour array was not supplied. Missing node identities cannot be reconstructed from edge identifiers.</p>
      <p v-if="!edges" role="status">The relationship array was not supplied. This is not an empty neighbourhood.</p><template v-else><p>{{ edges.length }} returned relationship records. Repeated dated edges remain separate.</p><div class="flex flex-wrap gap-2" role="group" aria-label="Commissioning presentation"><button type="button" class="atlas-button" :aria-pressed="view === 'diagram'" @click="filters.set('view', 'diagram')">Diagram</button><button type="button" class="atlas-button" :aria-pressed="view === 'data'" @click="filters.set('view', 'data')">Data</button></div><p v-if="!['diagram', 'data'].includes(view)" role="status">The saved presentation is not supported. Choose Diagram or Data.</p><div class="flex flex-wrap gap-2"><button type="button" class="atlas-button" @click="download('json')">Download displayed edges JSON</button><button type="button" class="atlas-button" @click="download('csv')">Download displayed edges CSV</button><button type="button" class="atlas-button" @click="download('references')">Download neighbourhood reference manifest</button></div><p class="atlas-footnote">Displayed-edge downloads cover the data page below. The manifest retains the complete returned neighbourhood, source caveat and missing metadata. Diagram exports identify their own displayed group.</p>
      <div class="st-directory-workspace" :class="{ 'has-inspector': hasInspector }"><div class="min-w-0 space-y-4"><template v-if="view === 'diagram'"><NuxtErrorBoundary><LazyStCommissioningDiagram :edges="diagramRows" :nodes="nodes" :selected="get('relationship_id')" :annotation="annotation" @inspect="(id, event) => inspect(id, event)" @node="(id, event) => inspect(id, event, true)" /><template #error="{ clearError }"><p role="status">The diagram could not load. The edge data and inspectors remain available below.</p><button type="button" class="atlas-button" @click="clearError()">Retry diagram</button></template></NuxtErrorBoundary><nav class="flex flex-wrap gap-2" aria-label="Diagram groups"><span class="atlas-footnote">{{ diagramRows.length }} edges in this group, starting at returned offset {{ diagramOffset }}.</span><button type="button" class="atlas-button" :disabled="!diagramOffset" @click="filters.set('diagram_offset', String(Math.max(0, diagramOffset - 12)))">Previous diagram group</button><button type="button" class="atlas-button" :disabled="diagramOffset + 12 >= edges.length" @click="filters.set('diagram_offset', String(diagramOffset + 12))">Next diagram group</button></nav></template>
      <div v-if="displayed.length" class="overflow-x-auto" role="region" aria-label="Commissioning edge data" tabindex="0"><table class="w-full text-sm"><caption class="text-left atlas-footnote">{{ displayed.length }} edges on this data page of {{ edges.length }} returned. Source-defined validity dates remain unchanged.</caption><thead><tr><th scope="col">Authority / subject</th><th scope="col">Provider / object</th><th scope="col">Validity</th><th scope="col">Evidence</th></tr></thead><tbody><tr v-for="(edge, index) in displayed" :key="`${edge.relationship_id}:${index}`"><td><button v-if="edge.subject_entity_id" type="button" class="atlas-button" @click="inspect(edge.subject_entity_id, $event, true)">{{ name(edge.subject_entity_id) }}</button><span v-else>Identifier not supplied</span></td><td><button v-if="edge.object_entity_id" type="button" class="atlas-button" @click="inspect(edge.object_entity_id, $event, true)">{{ name(edge.object_entity_id) }}</button><span v-else>Identifier not supplied</span></td><td>From: {{ edge.valid_from ?? 'not supplied' }}<br>To: {{ edge.valid_to ?? 'not supplied' }}</td><td><p>{{ edge.relationship_id ?? 'Relationship identifier not supplied' }}</p><p>Confidence: {{ edge.confidence ?? 'not supplied' }}</p><button v-if="edge.relationship_id" type="button" class="atlas-button" :aria-label="`Inspect relationship ${edge.relationship_id}, displayed row ${index + 1}`" @click="inspect(edge.relationship_id, $event)">Inspect relationship</button></td></tr></tbody></table></div><StEvidenceState v-else empty :empty-title="offset ? 'No edges on this display page' : 'No commissioning edges returned'" message="This does not establish that no commissioning activity occurred. Choose another centre or return to the first data page." /><nav class="flex flex-wrap gap-2" aria-label="Edge data pages"><button type="button" class="atlas-button" :disabled="!offset" @click="filters.set('offset', String(Math.max(0, offset - 25)))">Previous data page</button><button type="button" class="atlas-button" :disabled="offset + 25 >= edges.length" @click="filters.set('offset', String(offset + 25))">Next data page</button><button v-if="offset" type="button" class="atlas-button" @click="filters.set('offset', undefined)">First data page</button></nav></div>
      <StInspector v-if="hasInspector" :title="get('node') ? 'Graph entity' : `Relationship ${get('relationship_id')}`" @close="close"><p v-if="selectionConflict" role="status">The link requests both a graph entity and a relationship. Close this inspection and select one record.</p><template v-else-if="get('node')"><template v-if="selectedNode"><h3>{{ selectedNode.canonical_name ?? 'Name not supplied' }}</h3><dl><template v-for="(value, key) in selectedNode" :key="key"><dt>{{ String(key).replaceAll('_', ' ') }}</dt><dd>{{ connectionText(value) }}</dd></template></dl><p class="atlas-footnote">This node response supplies no public provider key, ONS code or source provenance. Inspect a relationship for its evidence and any supplied public identifiers.</p><button type="button" class="atlas-button" @click="save">Save connection reference</button></template><p v-else role="status">The graph identifier does not identify one returned node. Missing or conflicting identities remain unresolved.</p></template><template v-else-if="selected"><h3>{{ name(selected.subject_entity_id) }} awarded to {{ name(selected.object_entity_id) }}</h3><dl><template v-for="(value, key) in selected" :key="key"><dt>{{ String(key).replaceAll('_', ' ') }}</dt><dd>{{ connectionText(value) }}</dd></template></dl><StProvenance :provenance="selected" /><p class="atlas-footnote">The edge response does not supply a payload hash or a per-edge derivation type.</p><button type="button" class="atlas-button" @click="save">Save connection reference</button><LazyStCommissioningDetail :key="get('relationship_id')" :id="get('relationship_id')" @centre="centre" /></template><p v-else role="status">The saved relationship identifier does not identify one edge in this returned neighbourhood. No replacement has been selected.</p><p role="status">{{ status }}</p></StInspector></div>
      </template></template><p v-else role="status">The commissioning response was not supplied.</p>
    </StEvidenceState>
  </section>
</template>
<style scoped>th, td { text-align: left; padding: 10px; vertical-align: top; min-width: 145px; border-bottom: 1px solid var(--border-subtle); overflow-wrap: anywhere; } th, dt { color: var(--text-muted); } dt { margin-top: 10px; font-size: 12px; } dd { overflow-wrap: anywhere; } </style>
